- name: Include tasks
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  loop:
    - assert_extra_vars.yml
    - network.yml
    - root_email_address.yml
    - timezone.yml
    - acme_dns_authenticator.yml
    - acme_certificate.yml
    - iscsi.yml
    - ssh.yml
  tags:
    - truenas
    - main
