collections:
  - name: community.crypto
    version: 2.2.4
  - name: community.postgresql
    version: 2.2.0
  - name: community.general
    version: 4.7.0
  - name: kubernetes.core
    version: 2.3.2
  - name: nginxinc.nginx_core
    version: 0.6.0
