---
- hosts: all
  connection: local
  vars:
    packer_cache: /ansible/packer_cache
  tasks:
    - name: Install Prerequisites
      ansible.builtin.package:
        name:
          - genisoimage
      become: true
      tags:
        - install_prerequisites

    - name: Make cidata directory
      ansible.builtin.file:
        state: directory
        path: /packer/packer_cache/{{ ansible_host }}/cidata
        mode: 0644

    - name: Write Packer user-data Template
      ansible.builtin.template:
        src: "{{ user_data_template }}"
        dest: /packer/packer_cache/{{ ansible_host }}/cidata/user-data
        mode: 0644

    - name: Touch Packer meta-data Template
      ansible.builtin.file:
        path: /packer/packer_cache/{{ ansible_host }}/cidata/meta-data
        mode: 0644
        state: touch

    - name: build cidata iso
      ansible.builtin.command:
        argv:
          - genisoimage
          - -output
          - /packer/packer_cache/{{ ansible_host }}/cidata.iso
          - -volid
          - cidata
          - -joliet
          - -input-charset
          - utf-8
          - -rock
          - /packer/packer_cache/{{ ansible_host }}/cidata/user-data
          - /packer/packer_cache/{{ ansible_host }}/cidata/meta-data


# TODO: Add upload to Proxmox
