---
- hosts: localhost
  connection: local
  vars:
    packer_cache: /ansible/packer_cache
    cidata_path: /ansible/http/proxmox
    iso_path: cidata-proxmox.iso
  tasks:
    - name: packer_cache directory is present
      ansible.builtin.file:
        state: directory
        path: "{{ packer_cache }}"

    - name: Install Prerequisites
      ansible.builtin.package:
        name:
          - genisoimage
      become: true
      tags:
        - install_prerequisites

    - name: stat | http
      ansible.builtin.stat:
        path: "{{ cidata_path }}"
      register: http_stat_result

    - name: stat | http/meta-data
      ansible.builtin.stat:
        path: "{{ cidata_path }}/meta-data"
      register: metadata_stat_result

    - name: stat | http/user-data
      ansible.builtin.stat:
        path: "{{ cidata_path }}/user-data"
      register: userdata_stat_result

    - name: assert source files are present
      ansible.builtin.assert:
        that:
          - http_stat_result.stat.exists
          - metadata_stat_result.stat.exists
          - userdata_stat_result.stat.exists

    - name: build cidata iso
      ansible.builtin.command:
        argv:
          - genisoimage
          - -output
          - "{{ packer_cache }}/{{ iso_path }}"
          - -volid
          - cidata
          - -joliet
          - -input-charset
          - utf-8
          - -rock
          - "{{ cidata_path }}/user-data"
          - "{{ cidata_path }}/meta-data"

    - name: Get iso checksum
      ansible.builtin.stat:
        path: "{{ packer_cache }}/{{ iso_path }}"
        get_checksum: true
      register: checksum

    - name: Write checksum var file
      ansible.builtin.copy:
        content: cidata_iso_checksum = "sha1:{{ checksum.stat.checksum }}"
        dest: "{{ packer_cache }}/{{ iso_path }}.pkvars.hcl"

# TODO: Add upload to Proxmox
