- name: IPV4 - Always accept traffic from the loopback interface
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    jump: ACCEPT
    in_interface: lo
    wait: "{{ firewall_wait_lock_seconds }}"
  become: yes
  notify:
    - persist iptables

- name: IPV4 - Always accept traffic from the loopback interface
  ansible.builtin.iptables:
    table: filter
    chain: OUTPUT
    jump: ACCEPT
    out_interface: lo
    wait: "{{ firewall_wait_lock_seconds }}"
  become: yes
  notify:
    - persist iptables

- name: IPV4 - Block packets from 127.0.0.0/8 not received on the loopback interface
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    jump: DROP
    source: 127.0.0.0/8
    in_interface: "! lo"
    wait: "{{ firewall_wait_lock_seconds }}"
  become: true
  notify:
    - persist iptables
