- name: Install iptables
  ansible.builtin.package:
    name:
      - iptables
      - iptables-persistent
  become: true

- name: Create iptables configuration directory.
  file:
    path: /etc/iptables
    state: directory
  become: true

