- name: Add chart repos.
  community.kubernetes.helm_repository:
    name: rancher
    repo_url: "{{ rancher_chart_repo_url }}"
  tags:
    - rancher_monitoring
  become: true

- name: Install Rancher Monitoring CRD Chart
  community.kubernetes.helm:
    name: rancher-monitoring-crd
    chart_ref: rancher/rancher-monitoring-crd
    chart_version: "{{ rancher_monitoring_version }}"
    release_namespace: cattle-monitoring-system
    create_namespace: true
    kubeconfig: "{{ kube_config_file }}"
  become: true
  tags:
    - rancher_monitoring

- name: Install Rancher Monitoring Chart
  community.kubernetes.helm:
    name: rancher-monitoring
    chart_ref: rancher/rancher-monitoring
    chart_version: "{{ rancher_monitoring_version }}"
    release_namespace: cattle-monitoring-system
    create_namespace: true
    kubeconfig: "{{ kube_config_file }}"
    values: "{{ rancher_monitoring_helm_values }}"
  become: true
  tags:
    - rancher_monitoring
