---
- name: Get blkid for {{ item.src }}
  command:
    cmd: blkid -o value {{ item.src }}
  register: blkid
- name: Add fstab entry for {{ item.path }} directory
  ansible.posix.mount:
    state: present
    src: "/dev/disk/by-uuid/{{ blkid.stdout_lines[0] }}"
    fstype: ext4
    opts: "{{ item.options }}"
    path: "{{ item.path }}"
