---
cloudflare:
  api_token: "{{ lookup ('env', 'CLOUDFLARE_API_TOKEN') }}"
  zone: ryezone.com

kubernetes_api_server_port: 6443
kubernetes_zone: "{{ platform_environment }}.{{ cloudflare.zone }}"
kubernetes_advertise_address: "{{ ansible_all_ipv4_addresses[0] }}"
kubernetes_control_plane_endpoint_vip: "{{ kubernetes_api_server_vip }}"
kubernetes_control_plane_endpoint_port: "{{ kubernetes_api_server_port }}"

install_kubectl: false
kubectl_version: v1.20.7

cert_manager_cloudflare_api_token: "{{ cloudflare.api_token }}"
cert_manager_acme_email: esten.rye+acme@ryezone.com
cert_manager_helm_chart_version: 1.3.0

kubernetes_pki_directory: /var/lib/rancher/rke2/server/tls
kube_config_file: ~/.kube/config
step_password: "{{ lookup('password', 'files/secrets/step-ca_token_password chars=ascii_letters,digits length=64') }}"

python_virtualenv_directory: /opt/python_virtualenv_ansible
