---
cloudflare:
  api_token: "{{ lookup ('env', 'CLOUDFLARE_API_TOKEN') }}"
  zone: ryezone.com

kubernetes_api_server_port: 6443
kubernetes_zone: "{{ platform_environment }}.{{ cloudflare.zone }}"
kubernetes_advertise_address: "{{ ansible_all_ipv4_addresses[0] }}"
kubernetes_control_plane_endpoint_vip: "{{ kubernetes_api_server_vip }}"
kubernetes_control_plane_endpoint_port: "{{ kubernetes_api_server_port }}"

kubernetes_cni_calicoctl_version: v3.18.0
kubernetes_cni_calicoctl_checksum: sha256:7152bdda15c9fd2c4723004931def11989e20fa0884f4fc45ae8b61cc836cd19
kubernetes_package_signing_key_id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
kubernetes_kubeadm_release: xenial

helm_chart_version_cert_manager: 1.2.0
helm_chart_version_ingress_nginx: 3.23.0
helm_chart_version_kubernetes_dashboard: 4.0.2
helm_chart_version_linkerd: 2.9.4
helm_chart_version_prometheus: 13.13.1
helm_chart_version_openunison: 2.0.2
helm_chart_version_orchestra: 1.0.7

kubernetes_dashboard_namespace: kube-dashboard
kubernetes_dashboard_release: kube-dashboard

cert_manager_cloudflare_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"
cert_manager_acme_email: esten.rye+acme@ryezone.com
cert_manager_helm_chart_version: 1.3.0

# The subnets in this list are immediately dropped.
firewall_bogus_inbound_subnets:
  - 169.254.0.0/16
  - 172.16.0.0/12
  - 192.0.2.0/24
  - 192.168.0.0/16

# The subnets in this list are hostile and are dropped.
firewall_enemies_hostile_cidr: []
  # - 99.99.99.99

# These inbound services are not hosted externally and are dropped when requested
# on external interfaces.
firewall_enemies_inbound_services_not_exposed: []
  # - service: SQLServer
  #   protocol: tcp
  #   port: 1433

# The services in this list are high-priority packets from known inbound
# services like NTP that require relatively low packet processing delay.
firewall_always_high_priority_inbound_services:
  - service: NTP
    protocol: udp
    port: 123

# The subnets in this are trusted and are accepted.
firewall_friends_known_cidr:
  - 10.0.2.0/24
  - 10.5.0.0/16

# These services should only be accessed by sources we trust.
firewall_allow_inbound_services_exposed_to_friends:
  - service: SSH
    port: 22
    protocol: tcp

# These services are publicly advertised to the world.
firewall_allow_inbound_services_exposed_to_everyone: []
  # - service: HTTP
  #   protocol: tcp
  #   port: 80