# These services should only be accessed by sources we trust.
firewall_allow_inbound_services_exposed_to_friends:
  - service: SSH
    port: 22
    protocol: tcp
  - service: etcd client api
    protocol: tcp
    port: 2379
  - service: etcd peer api
    protocol: tcp
    port: 2380
  - service: Kubernetes API Server
    protocol: tcp
    port: 6443
  - service: RKE2 Node Join
    protocol: tcp
    port: 9345
  - service: Kubernetes Kubelet API
    protocol: tcp
    port: 10250
  - service: Kubernetes Kube Scheduler
    protocol: tcp
    port: 10251
  - service: Kubernetes Kube Controller Manager
    protocol: tcp
    port: 10252

# These services are publicly advertised to the world.
firewall_allow_inbound_services_exposed_to_everyone: []

firewall_bogus_block_loopback_subnet: false