firewall_allow_inbound_services_exposed_to_everyone:
  - service: etcd client api
    protocol: tcp
    port: 2379
  - service: etcd peer api
    protocol: tcp
    port: 2380
  - service: Kubernetes API Server
    protocol: tcp
    port: 6443
  # TODO: restrict 8472 to cluster nodes only.
  - service: RancherD/RKE2 Flannel VXLAN
    protocol: udp
    port: 8472
  - service: RancherD/RKE2 Node Join
    protocol: tcp
    port: 9345
  - service: Rancher Monitoring Node Exporter
    protocol: tcp
    port: 9796
  - service: Kubernetes Kubelet API
    protocol: tcp
    port: 10250
  - service: Kubernetes Kube Scheduler
    protocol: tcp
    port: 10251
  - service: Kubernetes Kube Controller Manager
    protocol: tcp
    port: 10252
