# The subnets in this list are high-priority packets from trusted sources
# like the Kubernetes pod and service networks that are managed using separate
# controls like Kubernetes Network Policy.
firewall_always_high_priority_inbound_subnets:
  - 10.42.0.0/16
  - 10.43.0.0/16

# These services should only be accessed by sources we trust.
firewall_allow_inbound_services_exposed_to_friends:
  - service: SSH
    port: 22
    protocol: tcp
  - service: etcd client api
    protocol: tcp
    port: 2379
  - service: etcd peer api
    protocol: tcp
    port: 2380
  - service: Kubernetes API Server
    protocol: tcp
    port: 6443
  - service: RancherD/RKE2 Flannel VXLAN
    protocol: udp
    port: 8472
  - service: RancherD/RKE2 Node Join
    protocol: tcp
    port: 9345
  - service: Kubernetes Kubelet API
    protocol: tcp
    port: 10250
  - service: Kubernetes Kube Scheduler
    protocol: tcp
    port: 10251
  - service: Kubernetes Kube Controller Manager
    protocol: tcp
    port: 10252

# These services are publicly advertised to the world.
firewall_allow_inbound_services_exposed_to_everyone: []

firewall_forward_chain: []

firewall_bogus_block_loopback_subnet: false