keepalived_virtual_router_id: "{{ virtual_router_id }}"
keepalived_auth_pass: "{{ virtual_router_auth_pass }}"
keepalived_vip: "{{ kubernetes_api_server_vip }}"
keepalived_interface: eth0
keepalived_check_port: "{{ kubernetes_api_server_port }}"

# These services are publicly advertised to the world.
firewall_allow_inbound_services_exposed_to_everyone:
  - service: HTTP
    protocol: tcp
    port: 80
  - service: HTTPS
    protocol: tcp
    port: 443
  - service: Kubernetes API
    protocol: tcp
    port: 6443
  - service: HAProxy Stats Page
    protocol: tcp
    port: 8000
  - service: RKE2 Node Join
    protocol: tcp
    port: 9345
  # - service: Step Certificates Certificate Authority
  #   protocol: tcp
  #   port: 32400
