- name: try to read key
  block:
    - name: Query HSM for key object - {{ key.label }}
      ansible.builtin.command:
        argv:
          - pkcs11-tool
          - --read-object
          - --type=pubkey
          - --pin={{ nitrokey_hsm_pin }}
          - --token-label={{ nitrokey_hsm_label }}
          - --label={{ key.label }}
      changed_when: false
      register: hsm_key_status_raw
      tags:
        - nitrokey_hsm_generate_certs
  rescue:
    - name: Generate Key - {{ key.label }}
      ansible.builtin.command:
        argv:
          - pkcs11-tool
          - --login
          - --pin={{ nitrokey_hsm_pin }}
          - --keypairgen
          - --key-type={{ key.key_type }}
          - --token-label={{ nitrokey_hsm_label }}
          - --label={{ key.label }}
      tags:
        - nitrokey_hsm_generate_certs

- name: Get Key PKCS11 HSM Data - {{ key.label }}
  ansible.builtin.shell:
    cmd: |
      pkcs11-tool --list-objects --pin={{ nitrokey_hsm_pin }} --token-label={{ nitrokey_hsm_label }} --type=privkey \
      | sed 's/Private Key Object;/\nPrivate Key Object;/g' \
      | sed '1d' \
      | awk -v label='{{ key.label }}' -v RS="" -F "\n  " '$2 ~ "label:      " label' \
      | awk '$0 ~ "  ID:"' \
      | awk '{ print $2 }'
  changed_when: false
  register: hsm_key_id
  tags:
    - nitrokey_hsm_generate_certs

- name: Debug ID - {{ key.label }}
  ansible.builtin.debug:
    var: hsm_key_id
  tags:
    - nitrokey_hsm_generate_certs

- name: Get PKCS15 HSM Data - {{ key.label }}
  ansible.builtin.shell:
    cmd: |
      pkcs15-tool --list-keys --short --pin={{ nitrokey_hsm_pin }} \
      | awk -v id='{{ hsm_key_id.stdout_lines[0] }}' '$2 ~ "ID:" id' \
      | awk '{ split($3, a, ":"); print a[2] }'
  changed_when: false
  register: hsm_key_ref_id
  tags:
    - nitrokey_hsm_generate_certs

- name: debug hsm_pkcs15_data - {{ key.label }}
  ansible.builtin.debug:
    var: hsm_key_ref_id
  tags:
    - nitrokey_hsm_generate_certs

- name: extract bank-vaults RSA Key Reference Id from PKCS15 output. - {{ key.label }}
  ansible.builtin.set_fact:
    hsm_key_ref_id: "{{ hsm_key_ref_id.stdout_lines[0] | int(base=16) }}"
  tags:
    - nitrokey_hsm_generate_certs

- name: debug hsm_key_ref_id - {{ key.label }}
  ansible.builtin.debug:
    var: hsm_key_ref_id
  tags:
    - nitrokey_hsm_generate_certs

- name: Export Generated bank-vaults RSA Key - {{ key.label }}
  ansible.builtin.command:
    argv:
      - sc-hsm-tool
      - --wrap-key=/etc/hsm/{{ hsm_key_ref_id }}.{{ key.label }}.wrap-key.bin
      - --pin={{ nitrokey_hsm_pin }}
      - --label={{ nitrokey_hsm_label }}
      - --key-reference={{ hsm_key_ref_id }}
    creates: /etc/hsm/{{ hsm_key_ref_id }}.{{ key.label }}.wrap-key.bin
  become: true
  when: nitrokey_hsm_export_certificates
  tags:
    - nitrokey_hsm_generate_certs

- name: create hsm certificate directory - {{ key.label }}
  ansible.builtin.file:
    state: directory
    path: "{{ nitrokey_certificate_dir }}"
    mode: 0750
  delegate_to: localhost
  tags:
    - nitrokey_hsm_generate_certs

- name: Fetch extracted key from node. - {{ key.label }}
  ansible.builtin.fetch:
    src: /etc/hsm/{{ hsm_key_ref_id }}.{{ key.label }}.wrap-key.bin
    dest: "{{ nitrokey_certificate_dir }}/{{ hsm_key_ref_id }}.{{ key.label }}.wrap-key.bin"
    flat: yes
  become: true
  when: nitrokey_hsm_export_certificates
  tags:
    - nitrokey_hsm_generate_certs
