- name: Assert values are defined
  ansible.builtin.assert:
    that:
      - nitrokey_hsm_sopin is defined
      - nitrokey_hsm_pin is defined
      - nitrokey_hsm_label is defined
      - nitrokey_hsm_dkek_share_password is defined
      - nitrokey_hsm_dkek_share_b64 is defined

- name: Query HSM for bank-vaults object
  ansible.builtin.command:
    argv:
      - pkcs11-tool
      - --list-objects
      - --pin={{ nitrokey_hsm_pin }}
      - --token-label=lab-hsm
      - --label=bank-vaults
  changed_when: false
  register: hsm_bank_vaults_status_raw

- name: Determine whether bank-vaults object is present
  ansible.builtin.set_fact:
    hsm_bank_vaults_present: "{{ hsm_bank_vaults_status_raw.stdout | length > 0 }}"

- name: debug hsm_bank_vaults_present
  ansible.builtin.debug:
    var: hsm_bank_vaults_present

- name: Generate bank-vaults RSA Key
  ansible.builtin.command:
    argv:
      - pkcs11-tool
      - --module=opensc-pkcs11.so
      - --login
      - --pin={{ nitrokey_hsm_pin }}
      - --keypairgen
      - --key-type=rsa:2048
      - --token-label=lab-hsm
      - --label=bank-vaults
  when:
    - not hsm_bank_vaults_present

- name: Get bank-vaults RSA Key PKCS11 HSM Data
  ansible.builtin.command:
    argv:
      - pkcs11-tool
      - --list-objects
      - --login
      - --pin={{ nitrokey_hsm_pin }}
      - --token-label=lab-hsm
      - --label=bank-vaults
      - --type=privkey
  changed_when: false
  register: hsm_bank_vaults_pkcs11_data

- name: Get bank-vaults RSA Key ID
  ansible.builtin.set_fact:
    hsm_bank_vaults_id: "{{ hsm_bank_vaults_pkcs11_data.stdout_lines[2] | replace(' ','') }}"
    hsm_bank_vaults_key_ref_regex: "\tRSA.+{{ hsm_bank_vaults_pkcs11_data.stdout_lines[2] | replace(' ','') }}.+"

- name: Assert ID starts with 'ID:'
  ansible.builtin.assert:
    that:
      - hsm_bank_vaults_id.startswith('ID:')

- name: Debug ID
  ansible.builtin.debug:
    var: hsm_bank_vaults_id

- name: Get PKCS15 HSM Data
  ansible.builtin.command:
    argv:
      - pkcs15-tool
      - --list-keys
      - --short
      - --pin={{ nitrokey_hsm_pin }}
  changed_when: false
  register: hsm_bank_vaults_pkcs15_data

- name: debug hsm_bank_vaults_pkcs15_data
  ansible.builtin.debug:
    var: hsm_bank_vaults_pkcs15_data
    verbosity: 2

- name: find bank-vaults RSA Key Reference Id
  ansible.builtin.set_fact:
    hsm_bank_vaults_pkcs15: "{{ hsm_bank_vaults_pkcs15_data.stdout_lines | select('match', hsm_bank_vaults_key_ref_regex)}}"

- name: extract bank-vaults RSA Key Reference Id from PKCS15 output.
  ansible.builtin.set_fact:
    hsm_bank_vaults_key_ref_id: "{{ (hsm_bank_vaults_pkcs15[0] | split(' ') | select('match', 'Ref:.+'))[0] | replace('Ref:', '') | int(base=16) }}"

- name: debug hsm_bank_vaults_key_ref_id
  ansible.builtin.debug:
    var: hsm_bank_vaults_key_ref_id

- name: Export Generated bank-vaults RSA Key
  ansible.builtin.command:
    argv:
      - sc-hsm-tool
      - --wrap-key=/etc/hsm/wrap-key-1_bank-vaults.bin
      - --pin={{ nitrokey_hsm_pin }}
      - --label=lab-hsm
      - --key-reference={{ hsm_bank_vaults_key_ref_id }}
    creates: /etc/hsm/wrap-key-1_bank-vaults.bin
  become: true

- name: Fetch extracted key from node.
  ansible.builtin.fetch:
    src: /etc/hsm/wrap-key-1_bank-vaults.bin
    dest: /tmp/pki/wrap-key-1_bank-vaults.bin
    flat: yes
  become: true
