- name: Assert values are defined
  ansible.builtin.assert:
    that:
      - nitrokey_hsm_sopin is defined
      - nitrokey_hsm_pin is defined
      - nitrokey_hsm_label is defined
      - nitrokey_hsm_dkek_share_password is defined
      - nitrokey_hsm_dkek_share_b64 is defined

- name: Generate Keys
  ansible.builtin.include_tasks:
    file: generate_key.yml
  loop_control:
    loop_var: key
  loop: "{{ nitrokey_hsm_keys_to_generate }}"
