- name: Assert values are defined
  ansible.builtin.assert:
    that:
      - nitrokey_hsm_sopin is defined
      - nitrokey_hsm_pin is defined
      - nitrokey_hsm_label is defined
      - nitrokey_hsm_dkek_share_password is defined
      - nitrokey_hsm_dkek_share_b64 is defined
  tags:
    - nitrokey_hsm_generate_certs

- name: Import OS Specific Variables
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}_{{ ansible_architecture }}.yml"

- name: Import OS Specific tasks
  ansible.builtin.include_tasks:
    file: "{{ ansible_os_family }}_{{ ansible_architecture }}.yml"

- name: Replace Lines in gpg-agent config files
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp}}"
    line: "{{ item.line }}"
    create: true
  loop:
    - regexp: ^scdaemon-program
      line: scdaemon-program {{ nitrokey_gpg_pkcs11_scd_path }}
      path: ~/.gnupg/gpg-agent.conf
    - regexp: ^pinentry-program
      line: pinentry-program {{ nitrokey_pinentry_path }}
      path: ~/.gnupg/gpg-agent.conf
    - regexp: ^providers
      line: providers nitrokey
      path: ~/.gnupg/gnupg-pkcs11-scd.conf
    - regexp: ^provider-nitrokey-library
      line: provider-nitrokey-library {{ nitrokey_hsm_module_path }}
      path: ~/.gnupg/gnupg-pkcs11-scd.conf


- name: Generate Keys
  ansible.builtin.include_tasks:
    file: generate_key.yml
  loop_control:
    loop_var: key
  loop: "{{ nitrokey_hsm_keys_to_generate }}"
  tags:
    - nitrokey_hsm_generate_certs

- name: Generate Keys
  ansible.builtin.include_tasks:
    file: generate_gpg_cert.yml
  loop_control:
    loop_var: gpg_cert
  loop: "{{ nitrokey_hsm_gpg_certs_to_generate }}"
  tags:
    - nitrokey_hsm_generate_certs
