
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-server
  namespace: csi-driver-nfs
  labels:
    app-stack: csi-driver-nfs
    component: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app-stack: csi-driver-nfs
      component: nfs-server
  template:
    metadata:
      name: nfs-server
      labels:
        app-stack: csi-driver-nfs
        component: nfs-server
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:latest
          env:
            - name: SHARED_DIRECTORY
              value: "/exports"
          volumeMounts:
            - mountPath: /exports
              name: nfs-vol
          securityContext:
            privileged: true
          ports:
            - name: nfs
              containerPort: 2049
              protocol: TCP
            - name: rpcbind
              containerPort: 111
              protocol: UDP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 200Mi
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
          claimName: nfs-vol
