---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
  namespace: csi-driver-nfs
  labels:
    app-stack: csi-driver-nfs
    component: nfs-server
spec:
  type: ClusterIP
  selector:
    app-stack: csi-driver-nfs
    component: nfs-server
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
      targetPort: nfs
    - name: rpcbind
      port: 111
      protocol: UDP
      targetPort: rpcbind
