collections:
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 4.6.1
  - name: community.kubernetes
    version: 2.0.1
  - name: community.crypto
    version: 2.2.4
  - name: nginxinc.nginx_core
    version: 0.5.0

roles:
  - name: darkwizard242.cis_ubuntu_2004
    version: 3.1.0
  - name: gantsign.antigen
    version: 1.4.0
  - name: gantsign.antigen_bundles
    version: 1.3.0
  - name: gantsign.golang
    version: 2.10.0
  - name: sicruse.powerline-fonts
    version: v1.2.1
  - name: alvistack.obs_studio
    version: 5.5.6
