collections:
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 3.7.0
  - name: community.kubernetes
    version: 2.0.0
  - name: community.crypto
    version: 1.9.4
roles:
  - name: darkwizard242.cis_ubuntu_2004
    version: 1.0.2
  - name: gantsign.antigen
    version: 1.4.0
  - name: gantsign.antigen_bundles
    version: 1.2.0
  - name: sicruse.powerline-fonts
    version: v1.2.1