all:
  children:
    external_load_balancer:
      hosts:
        haproxy01:
          ansible_host: haproxy01.prod.ryezone.com
        haproxy02:
          ansible_host: haproxy02.prod.ryezone.com
      vars:
        haproxy_frontends:
          - name: api-server
            bind_address: "*"
            bind_port: 6443
            mode: tcp
            default_backend: api-server
            options:
              - tcplog
          - name: node-join
            bind_address: "*"
            bind_port: 9345
            mode: tcp
            default_backend: node-join
            options:
              - tcplog
          - name: http-ingress
            bind_address: "*"
            bind_port: 80
            mode: tcp
            default_backend: http-ingress
            options:
              - tcplog
          - name: https-ingress
            bind_address: "*"
            bind_port: 443
            mode: tcp
            default_backend: https-ingress
            options:
              - tcplog
          - name: https-stepca
            bind_address: "*"
            bind_port: 32400
            mode: tcp
            default_backend: https-stepca
            options:
              - tcplog

        haproxy_backends:
          - name: api-server
            mode: tcp
            port: 6443
            balance_method: roundrobin
            options:
              - httpchk GET /healthz
              - ssl-hello-chk
            http_checks:
              - expect status 200
            servers: "{{ rke2_controlplane_servers }}"
          - name: node-join
            mode: tcp
            port: 9345
            check_options: check-ssl verify none
            balance_method: roundrobin
            options:
              - httpchk GET /ping
            http_checks:
              - expect status 200
            servers: "{{ rke2_controlplane_servers }}"
          - name: http-ingress
            mode: tcp
            port: 80
            balance_method: roundrobin
            options:
              - httpchk GET /healthz
            http_checks:
              - expect status 200
            servers: "{{ rke2_ingress_servers }}"
          - name: https-ingress
            mode: tcp
            port: 443
            balance_method: roundrobin
            options:
              - httpchk GET /healthz
              - ssl-hello-chk
            http_checks:
              - expect status 200
            servers: "{{ rke2_ingress_servers }}"
          - name: https-stepca
            mode: tcp
            port: 32400
            balance_method: roundrobin
            http_checks:
              - expect status 200
            options:
              - httpchk GET /health
              - ssl-hello-chk
            servers: "{{ rke2_ingress_servers }}"

    kubernetes_cluster:
      children:
        controlplane:
          children:
            initial_controlplane:
              hosts:
                controlplane01:
                  ansible_host: controlplane01.prod.ryezone.com
            additional_controlplane:
              hosts:
                controlplane02:
                  ansible_host: controlplane02.prod.ryezone.com
                controlplane03:
                  ansible_host: controlplane03.prod.ryezone.com
        nodes:
          hosts:
            node01:
              ansible_host: node01.prod.ryezone.com
            node02:
              ansible_host: node02.prod.ryezone.com
            node03:
              ansible_host: node03.prod.ryezone.com
      
  vars:
    ansible_user: automation-user
    platform_environment: prod
    install_rancher: false
    taint_server_nodes: true
    kubernetes_api_server_vip: 10.5.100.3
    virtual_router_id: 53
    virtual_router_auth_pass: 79
    dns_entries:
      - record: haproxy01
        value: 10.5.100.1
      - record: haproxy02
        value: 10.5.100.2
      - record: kube-api
        value: 10.5.100.3
      - record: "*"
        value: 10.5.100.3
      - record: controlplane01
        value: 10.5.100.11
      - record: controlplane02
        value: 10.5.100.12
      - record: controlplane03
        value: 10.5.100.13
      - record: node01
        value: 10.5.100.31
      - record: node02
        value: 10.5.100.32
      - record: node03
        value: 10.5.100.33

    # The subnets in this are trusted and are accepted.
    firewall_friends_known_cidr:
      - 10.0.2.0/24
      - 10.5.0.0/24
      - 10.5.100.0/24
