tftp_user: tftp
tftp_uid: 35000
tftp_group: tftp
tftp_gid: 35000
tftp_directory: /var/lib/pxeroot
tftp_address: :69
tftp_options:
  - --secure

image_mirror_dir: "{{ tftp_directory }}/images"
imagemirror_on_calendar: '*-*-* 02/6:30:00'
imagemirror_accuracy_sec: 1m

talos_linux_version: v1.3.0
image_mirrors:
  - name: ubuntu
    mirror: rsync://mirror.math.princeton.edu/pub/ubuntu-iso/
