apt_repos:
  - name: linux-surface
    repo: https://pkg.surfacelinux.com/debian release main
    arch: amd64
    key_url: https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc
