apiVersion: openunison.tremolo.io/v1
kind: PortalUrl
metadata:
  name: grafana
  namespace: openunison
spec:
  label: Grafana
  org: B158BD40-0C1B-11E3-8FFD-0800200C9A66
  url: https://grafana.dev.ryezone.com
  icon: |
    iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAMAAACahl6sAAAABGdBTUEAALGPC/xh
    BQAAAAFzUkdCAK7OHOkAAAAJcEhZcwAAAEgAAABIAEbJaz4AAAMAUExURUxpcfR2
    KPeMJPNuKPiSIv7HEv7IEfeRIfiVIPV7J/meIvJjKfFZKv/SDPaIJv/YCv24GfaF
    JvmcI/RzKPNvKfNrKf/cB/aIJv2yHPJeKfqjIfeQJfulIPaHJvqlIf/jBPqgIfeR
    JfNnKfaJJv/XCfFZKvFaKvJgKfeMJviZJPePJfyrH/ytHv/GEfFZKv/rAfJjKfyu
    HvRyKPmgIvR4KPV6J/ePJfaJJvaCJ/JdKfupIPywHf/MDvR3KPRzKP/LDv/qAfiX
    JfR2KPyuHfRvKf/NDf/HEf/NDfeLJvaBJ//qAfuqH/V9J/R4KPeSJfNuKfywHfeN
    Jf/PC/JaKv/CFPyuHveRJfV7J//JD/2yHPaEJvaCJ//ODP/TC/FZKvNpKf/sAfur
    H/eLJvmcI/R4KPupIP/mAv/SCf/DE/qlIfJeKf/HEfFZKvR0KPV/J//vAP/rAf/D
    E/67F/++FvFZKvJoKfJhKfNrKfeLJviYJP/vAPytHvqjIfNuKfaIJvRzKfJmKfWA
    J/NtKf/pAfNtKf/sAfulIf/NDPR1Kf+/Ff/CE//oAf/LDvR4KP/SCf/mAv/oAviX
    JPeOJf/MDf/pAf/EE//PC/22Gv/RCv/SCfeSJf/rAf/dA/mgIv/aA//jAv/cA//D
    E//yAP+/Ff/FE//PC//CE/FZKv/AFPV/J//EE//WBvaJJv/mAv24GfaHJ/yuH/aE
    J/aGJ//NDP20G/WCJ/R2KPWBJ//SCfeSJf69FvV8J//XBP/GE/JmKf/IEf/bA/67
    GPqjIv/RCvJjKfR6J/iXJfmeI/mgIvaMJvJiKf/eA/FfKfJnKfFdKfFbKv/hAvur
    H/aNJv/QC/upH//LDveQJfNzKfR4KP/nAvuoIPyyHPJpKfywHvqmIPeUJfeVJfNr
    KfibJPiaJfNtKf/BFP/TCfNvKf/FE/68F//YBP/aBP/dA/66GP/gAv/KD//iAv/k
    AvuqH/22G/aOJv/wAP/sAf/tAP/yAPqkIvN0KficI//oAvNwKf/pAv/rAmFjIaIA
    AACndFJOUwARCSUFDQcBAgwhNPkrWB89TBoqHRcYeChBaPXaLacyFUJX8RHvwGin
    0WBbM0/m3kqTnX897jKV93W9gtqPcY5p6/ROw75Ygd3UvfqnZuWprdGuhMvywfun
    3eiIbUHb8dLrtPnmcVuZZ+nO7q3OyPWP2u6+nPqTu2iHnstK2fn64N1+yuZI9OXd
    m+Wu+bX27/q1/PR/dtD47Pue59qS+Kjs9e30+fv5ohwB0wAAD69JREFUeNrUXGtM
    W9cd59rX3Htt6tnYnsHYFo8GAyYIG2ODLVzxUAfC5iECFNCCeEkBBaTyRgQCCCFS
    iQ9EmiJFyqd8cCpVSajaRuukSpu6bou6Tp2ipWrSLO0mRfnQL+u+dFOlGYLBj/s/
    59xrX5v9PiW65/x/53f+r3PutcjKSha2UBg5PVzW/zmY+VBKlTAGPZsRIVxpKJVK
    ONvURVVGhMgvhlKnhFFdzgmF6jMiJD8nFFGySCXtjqNdWcyIEFvoBDmX9cm7I4zL
    dCaEzIeiUJpEeFP1kSAtzUQFpEqjhYQuFossOWzEHYdGDJnI9aoYIaFz9Zw4d0TZ
    qZJnQEh1TqyQUM688ERh8y9HmzmXnwEh9aEECE6UGHcc7kVx+nWw84lCwolCC3JH
    abxXbZnr63GJ0kPeUQw9VQnzezKf6ycdRS7aHWHMs5nP9QimqlmR7jjMMvos5Hqk
    htqwdZiuLuXfhynqTOQ6aR029JwDpl5MeyOhSkMIIOtw2B3gxHNpP8jrqlBCUHVY
    D7rj0JnVZybXY+swQ1MGvVylyj+CSiVX2aaQM21nJ9dP6nBxfnH94uXSqYtVVeeO
    Ef4XZgPqz1Cun0jJyQkJRrqvVtRUSBqk+2qFyXXxKKXOVq6LRrqvVvV/kQhpvlqx
    81IJSfPViir9QiKkuSPqqqQS8oUtzbn+uVRI79WqXjIdn6e1/rKdDyXDcDrfP1BT
    0gl5uJHGuqXb+FQ6PNywydKW6wufSonhRX16dDA9n0iMpfRcFF0bUgv5ZKNY+lMw
    kz/1Z+kxXC/1Fwa6eEPoop4uDG9MtXQ6F7fqbYfwby12Lk1tLzxFTVpYlLahcFvD
    T4VgeGPJWV+skhtkNMucepWVGXTVfmfL8AI4c6FTypTXOxcEiFjr9OfLOfjFI0up
    bJ1roMUl6Y70uqVvSbG9tJVvIHh5SuuLnWsLvCaetuikKlfThCqGW7ZUHEOcdnLb
    0jCvHWmUMNVr/yTC2mK+0JLD5Tu3v+UxJYUSpnibRMWLab9cTA+gVQ3bL9KhhKne
    foHHTy1B0W8PWF0DD0VLqjO+eo1Ax7Q/qZcgtMo5nGAztbWLK979CYvtraQrP129
    dDXebGdK3hCxMkqvcwX3mh7jcLVTlYrvZpR/N96yM5keT3MGnavY39DZMr02jlfx
    +PFuMFU/29I54/iuNshEOMAgV1UHt8ICwuu/+pgUYXcwKYtjWXAt1nqTn7QOshyl
    V1WHHRBomd6tvfofoajdSu0JT9cZu4Za7EWepQ4DaMi5N70bdsBHIrGb8tsD5x+P
    ZXBhMsE/ncT6I2iR4D7HulpiOKbRjZEOfJQ0vpLouK13NkXT7KGLsLb2qyTR7yQs
    80y4kFtcLq1a63LpDBRNEl7RROjSRTckq6OBJM1pvSvYsDc9Pl7b1NTf1FQ7vjsT
    GFKrMMd8VtsWxdQURNZF/czvk0H/EL57yCzBQFttf+Lc2mln0IKcb9mLGj9ehAmu
    ZHQ4cTpYeXBvvB82ML7ntyCiTB+ImjsjRwfXb0SjH3d4oF0Nm/04K+MBtQGMGqoh
    an6AQgeXaCEBA0aGc5xsQ2aMcihdZMba03FGZFKpa98VB7SrGXnDILmtzSELsEg6
    eLq+Wi06uMTpaHMji2ewTZi5zSEdf4DR6tMNaUP2RfmMGB3o3dEF6gRb3DTyt1Ym
    Sgk6TdTCSd+tQ8VruAOI2ZsHM2qO39wmEW2WzPNAMAKIwivzDz4Qh7qAhTe+tJuR
    EYPIbiJv+1AgUMHKDdV9KBqb/Bc07WBkwAzyaFchkLpOjbisepLQETbt0fPnSWSA
    B3VMkwUOBMEDn+A4T91BcphxMbxKjh+XqJFVpk0IVRvcQWRDyeo4ONhU82w6u1yC
    Zz8KLnKiumW4XhmT13FwMGjM5uknJ6aRwcWVvU+MUbiYawffTwVKjByfs9ePnyJb
    mKX1HiEQdixt91KD9SEZXxk5fjqTi1KyvE5IUgZmOjV6L1VY54uu3Ij9IRYZXO8R
    oQRuScZ1xLz1ktbuMAZLCGmWeRar6371cNCNDi4iBtghbtDAemuZUetWFhYW5upc
    FUN9gyRK+Mps0THFTRk6uEjsgxkig1w6WKZWRhcahnMb+/COaeVzvboEs4pXwfUn
    PEbBQ5a2hHdC65Cbp1xS2rISHFW3nK8Ir79aBvIY7G7F6rheAWc63/gSD3RjkhWN
    FmDIynhWy908elSA7O9ZywV/xaBVCTqEZ+71Pi2ieXEV3Wiy63yHdmXf0TO0S7gy
    nBAPA2ZI4uACTy767YTSU4Jk6yjiTfgj22iXWFr/jUQBmGTujoTBHRXZuJde2epu
    JF8fz04wFQWHj0Y5THD9DYVucIuNCWNbi0i+mVhGr6MIV3iCi145nFKAfmHH3UQK
    uQm1VK4vfmhHEeHHthXU3vFaocoOH3nQb1wt3QizcM1yN8YNLagg/kK13IGg5E1q
    ZR8yOo4P9AW/BtFhAWfFD71J/uGPVXfAlPwb4u4OP9FiNqgMttoHJpgnXrJbyAdQ
    lBL+jdeGZxgxZrWwS8Diy+3HjxT0rRqpxAgEDqYAhw/L5X+HAF4NC+PmNBZlCQJT
    0QiSliv5C3cF7lMAt/8cAFzxlB2xI/uEfnWnjQUQ6/MasT8WKIMsdoDnE0tjstzc
    TVBIuVKckOz9zwCUF8LVN2bg8yvCaZV9EO1nRnFCKNDivoxQSKNbBG9RI7iBuaKE
    5JZDBsG+Hg6tWGYxwcCuQLxjFaKEWBr/AWAFFt8RMxCOQfQOQsT7on6xUwQKgVOY
    Kk+BkKyKMYBYaDU/vhaPfQfABBcIa8xAkXWG2oeYV8SYM30nXEjWSsxAUcmO2kNR
    6T7xXwgIIc1j0QPHrogtmACzKIM1f4CAEKI0x4xcESckywRR30qXENoaM1Jktsfv
    R3IGRQnJMo1FjxyzixPC3gKod0TUrZo/QphA7mXMUK9IlzSPieAWLKQGuZdxY8X9
    eDbXDHBb6RQKQWZc5WTM2MlmcUdvK8AtogDX/A4CclfYW7GDzVdE/YJ2AuCerBRe
    AkEhXgVqXp45jtqEeP+ggEwV7QDk9hR6xIx2ryluDTvWPDAVrNZcqGgA5IJbU6H3
    RwiTeciZCmv8BLOd/9jK1oC2FBC90Gyna358BmEHc1BwmxNmWDV8/Fcmn0HeZa0A
    +apCmBD7zjMYJlwXmEyYMumoTHiVrQkLtkIJ5AO4zcJO1JVmhI5nDkwhYk082zBp
    bc6NbioKuxm1JyaAe0RQ2VJ6v0bBi7up0RM7PNN2Vh32ysJslmHYbKW963AIvL/N
    7fzc7UIOwArrIyTMedgUM43wzmwfWfVaHQ6r19x+9F/4xKFp5+f+2iQk0dvRQgh2
    hbWbH+HRVShYyCMH+aHHPvIvDHwkaeZtx5lZRXi2EloEPhxOE/1LHLpIPhYU+kbQ
    VryoJVWCk30saaJjdXw5SbQrtKarF7bR60AeEGAhI1cIE/0+Hu2EJx5Fc1cvYMHb
    jP5EqukF2VdJWgntaycQcp/4oCDTOFYTl9TrteNuXBrEOhwEkW3vJdFxf4C8v7K5
    zT7vwKnZ3gGvT4M/Z9gR7L34gNAM3CeDSUh/ZWRKjX3C53A4fBN2jVJGckOZQO4j
    rr0rV78hRJfUf37Fh6ZHu1TR9YQUvRppddDopdxAvoTI9n1DLOSJQ9o/ZVu4iqZH
    Bpepl1zHk4E8SYXkjWD4EcGlGfhACHySCrHfwNDDwZW3KkjHB9K6xIHnB4KrsOsH
    gZDSJYo5PD9/cMkcP9wViIFK6YRoZvH8Ny7xtaxLN+4KxrVs6boI0U7yBHfzrHAd
    d2ebJSu+c2Q7mdCVKy98LwZzuRIJOX+DiH/2zfgXfnPfi4NPmj/kld1FyH8hNrgU
    134rErPnJUp10gU4otOU/dXtl2JxQYpmkn2NmD9mJ8/Pfiweb72eeiHNAhZ04Wen
    if52EjpevvxFymvw63NCFvBGJE1/PncnGXx8+1Kqj8GXbgtZwElw/fL2neTwzptM
    SnW89rYw/khwvfbOnWSVpLQvKt4Syv/Gq+D+X3dnz9o2EAbgG3yylkOeRDdl0Gr8
    BwTSIgk0mgwaJNBkBTTYJptXY0xiYxv8gUNCkqZNh5ZMXjo0pNCxSyF06A9oCW1p
    2iFNhpDWTuo2TmznTtKdoc+uu3v03nufMuaN5fXHHyNRjNGE7z4jrf7Jn2kxKaN0
    d21o8zw0xXRsvcsIyKu/PQfw8JHbXVsNa7NuxDTFp4phqrfvLOh5KLgra6vFEDaB
    E8upCloO9R6fOtN+1guF1Iq6WgxOiHisLsXhcRKOdXfWidrY5hCbkyyK7nEYFl2Y
    dz7IiSnDtJeDp3iFFY1ok3wqvMfhifnwCm4JGWvFwyMMAlWMMO4aylEEbLxKhC5e
    LXo67OgFu0EUDwV3P5GU9FMcAlUIlx52/ZSco3q7qixnfXMF4S/4BDyT055DvrCH
    KwqRQD2oKvqo/ekUEmCCcNWKeu+xqOtpsq8s+JTdxis5UHq6rY7a/0iUudCrCaM9
    wKOdJVDhkVrFKbRqOy4SZC4RfTXEqYMBvoqMqWEqOAXWbSnGDZyoD/BVdEd4sO9C
    Fy8ag7YJQZxICr7JYF/x0+IcFw45eh+zqNj300b/mIRGzzeQPO3XqWLKyVb3ccvJ
    xn7CwTuNYzL2q7o/ylLIJUZfBSU4WZDSpt0jeSM9BGKHMxtvyGn0h+Nm1vZ9O6v3
    lP4G2dN9KqeAUN14yZaGQ+e2EqoNph4bJq3LC2g2PrFjw4eAFpzTf8EMGkey/8au
    XIOVR1YENIH6/+EBgPqKBds+bQ/gMPFQZdoewNj+TJ1dE1L3AO7uF9ps5Vj83Sba
    fU0Zy00y8ADiFl2NbV8ATJAtqh5bOcjGA3A7X+mxvYOSgBX+W2qwC8eIDj0PCbBE
    +0aLDlMPUPn2jg67bAMCpOZ3OtQgWxGUoSSisfUAYvkHFZqMexbgLDoiZZmxCL9D
    R6QAWFM4mEOrXCjUvOYBMa0ccxHtw2wympgEnOhqBctrtg4+4LOJmIvkWpczaNWk
    5L97YamidUo1q+xlrvHKQ7fLmViQuUileTWdjAbv33NDWRSuEWUourXWjGev2KcI
    QJtTW3IrHHPG7kJ+hgj7FAFC5tcUMhrW8Mlpm9Oe/rUpsReRyz/vkd+RMDcSfMX7
    OQXms8jopdbO7zIlO+Ys1qzz+5R49iKgdKcR+ZJEtK8TSvl7ItoCPEDnbAKPeF8n
    d/KTRZzlK4sQ0SaaUAoxkw1TflIkIyxCpJKPEo6b+aXiTYgsYDocZetepHCMU/62
    SGERHsOt1cUNXi7C3ZhYOrv4y0JyHYjedeV7hWgdG3b2xh55dyEinDWqvFyJelWZ
    yI1Du5hcB3wpejjGiXIjYkV6J78BgvCuRSieTtcAAAAASUVORK5CYII=
  azRules: []