apiVersion: openunison.tremolo.io/v1
kind: Trust
metadata:
  name: grafana
  namespace: openunison
spec:
  accessTokenSkewMillis: 120000
  accessTokenTimeToLive: 60000
  authChainName: LoginService
  clientId: grafana
  clientSecret:
    keyName: grafana_oidc_client_secret
    secretName: orchestra-secrets-source
  codeLastMileKeyName: lastmile-oidc
  codeTokenSkewMilis: 60000
  publicEndpoint: true
  redirectURI:
  - https://grafana.dev.ryezone.com/login/generic_oauth
  signedUserInfo: false
  verifyRedirect: true