---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml
driver:
  name: vagrant
verifier:
  name: testinfra
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  playbooks:
    converge: ../../playbook.yml
platforms:
  - name: controlplane01
    groups:
      - all
      - controlplane
    box: geerlingguy/ubuntu2004
    box_version: 1.0.2
    memory: 2048
    cpu: 2
    interfaces:
      - network_name: private_network
        type: static
        ip: 10.5.99.21
        auto_config: true
  - name: controlplane02
    groups:
      - all
      - controlplane
    box: geerlingguy/ubuntu2004
    box_version: 1.0.2
    memory: 2048
    cpu: 2
    interfaces:
      - network_name: private_network
        type: static
        ip: 10.5.99.22
        auto_config: true
  # - name: controlplane03
  #   groups:
  #     - all
  #     - controlplane
  #   box: geerlingguy/ubuntu2004
  #   box_version: 1.0.2
  #   memory: 2048
  #   cpu: 2
  #   interfaces:
  #     - network_name: private_network
  #       type: static
  #       ip: 10.5.99.23
  #       auto_config: true
  # - name: node01
  #   groups:
  #     - all
  #     - node
  #   box: geerlingguy/ubuntu2004
  #   box_version: 1.0.2
  #   memory: 2048
  #   cpu: 2
  #   interfaces:
  #     - network_name: private_network
  #       type: static
  #       ip: 10.5.99.31
  #       auto_config: true
  # - name: node02
  #   groups:
  #     - all
  #     - node
  #   box: geerlingguy/ubuntu2004
  #   box_version: 1.0.2
  #   memory: 2048
  #   cpu: 2
  #   interfaces:
  #     - network_name: private_network
  #       type: static
  #       ip: 10.5.99.32
  #       auto_config: true
  # - name: node03
  #   groups:
  #     - all
  #     - node
  #   box: geerlingguy/ubuntu2004
  #   box_version: 1.0.2
  #   memory: 2048
  #   cpu: 2
  #   interfaces:
  #     - network_name: private_network
  #       type: static
  #       ip: 10.5.99.33
  #       auto_config: true
