- hosts: localhost
  connection: local
  vars:
    packer_version: 1.7.10
    packer_arch: "{{ ansible_architecture | lower }}"
  tasks:
    - ansible.builtin.set_fact:
        packer_arch: arm64
      when:
        - packer_arch == 'aarch64'

    - ansible.builtin.set_fact:
        packer_arch: amd64
      when:
        - packer_arch == 'x86_64'

    - ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - ansible.builtin.apt:
        update_cache: false
        install_recommends: false
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - genisoimage
          - gpg
          - isolinux
          - mkisofs
          - p7zip-full
          - ssh
          - sudo
          - unzip
          - xorriso

    - ansible.builtin.debug:
        var: ansible_architecture

    - ansible.builtin.get_url:
        url: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_{{ packer_arch }}.zip
        dest: /tmp/packer.zip
        mode: 0755

    - ansible.builtin.unarchive:
        src: /tmp/packer.zip
        remote_src: true
        dest: /usr/local/bin

    - ansible.builtin.command:
        cmd: apt clean

    - ansible.builtin.group:
        name: automation-user
        gid: 1000

    - ansible.builtin.user:
        name: automation-user
        uid: 1000
        shell: /bin/bash
        groups:
          - sudo

    - ansible.builtin.file:
        path: /ansible
        state: directory
        recurse: true
        owner: automation-user
        group: automation-user

    - ansible.builtin.file:
        state: absent
        path: /var/lib/apt/lists

    - ansible.builtin.file:
        state: absent
        path: /tmp

    - ansible.builtin.file:
        state: directory
        path: /tmp
        mode: 0777
