# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "oj", "= 3.13.11"

gem "json", "= 2.6.1"

gem "async-http", "= 0.56.5"

gem "ext_monitor", "= 0.1.2"

gem "fluentd", "= 1.14.6"

gem "bigdecimal", "= 3.1.2"

gem "fluent-plugin-s3", "= 1.6.1"

gem "fluent-plugin-elasticsearch", "= 5.2.4"

gem "elasticsearch", "= 7.17.1"

gem "fluent-plugin-record_splitter", "= 0.2.1"
