---
- hosts: default
  become: true
  tasks:
    - name: udpate apt-cache
      ansible.builtin.apt:
        update_cache: true

- hosts: default
  become: true
  vars:
    ubuntu_2004_cis_section3_rule_3_5_3_2_1: false
    ubuntu_2004_cis_time_synchronization: chrony
    ubuntu_2004_cis_firewall: iptables
    ubuntu_2004_cis_require_ssh_ciphers: aes256-ctr,aes192-ctr,aes128-ctr
    ubuntu_2004_cis_require_ssh_macs: hmac-sha2-256,hmac-sha2-512
    ubuntu_2004_cis_require_ssh_kexalgorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
    ubuntu_2004_cis_section5_rule_5_2_2_params_permissions_command: find /etc/ssh -xdev -type f -name 'ssh_host_*_key' -exec chmod u-x,go-rwx {} \;
    ubuntu_2004_cis_section5_rule_5_2_3_params_permissions_command: find /etc/ssh -xdev -type f -name 'ssh_host_*_key.pub' -exec chmod u-x,go-rwx {} \;
  roles:
    - darkwizard242.cis_ubuntu_2004

- hosts: default
  become: true
  tasks:
    - name: udpate apt-cache
      ansible.builtin.apt:
        update_cache: true

- hosts: default
  become: true
  vars:
    ubuntu_2004_cis_section1: false
    ubuntu_2004_cis_section2: false
    ubuntu_2004_cis_section3: true
    ubuntu_2004_cis_section4: false
    ubuntu_2004_cis_section5: false
    ubuntu_2004_cis_section6: false
    ubuntu_2004_cis_firewall: iptables
  roles:
    - darkwizard242.cis_ubuntu_2004
  tasks:
    - name: remove files
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
        - /etc/netplan/00-installer-config.yaml
        - /etc/netplan/50-cloud-init.yaml
        - /etc/udev/rules.d/70-persistent-net.rules
        - /etc/cloud/cloud.cfg.d/99-pve.cfg

    - name: set persistent net rules
      ansible.builtin.copy:
        content: SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{dev_id}=="0x0", ATTR{type}=="1", NAME="eth0"
        dest: /etc/udev/rules.d/70-persistent-net.rules

    - name: set cloud-init config
      ansible.builtin.copy:
        content: "datasource_list: [ConfigDrive, NoCloud]"
        dest: /etc/cloud/cloud.cfg.d/99-pve.cfg

    - name: clean cloud init
      ansible.builtin.command: cloud-init clean

    - name: remove /var/log contents
      file:
        path: /var/log/{{ item }}
        state: absent
      when: item != 'audit'
      become: true
      with_fileglob:
        - /var/log/*
