- name: Add chart repos.
  kubernetes.core.helm_repository:
    name: rancher
    repo_url: "{{ rancher_chart_repo_url }}"
  tags:
    - rancher_monitoring

- name: Install Rancher Monitoring CRD Chart
  kubernetes.core.helm:
    name: rancher-monitoring-crd
    chart_ref: rancher/rancher-monitoring-crd
    chart_version: "{{ rancher_monitoring_version }}"
    release_namespace: cattle-monitoring-system
    create_namespace: true
  tags:
    - rancher_monitoring

- name: Install Rancher Monitoring Chart
  kubernetes.core.helm:
    name: rancher-monitoring
    chart_ref: rancher/rancher-monitoring
    chart_version: "{{ rancher_monitoring_version }}"
    release_namespace: cattle-monitoring-system
    create_namespace: true
    values: "{{ rancher_monitoring_helm_values }}"
  tags:
    - rancher_monitoring
