- hosts: localhost
  connection: local
  vars:
    maintainer_name: Ryezone Labs
    maintainer_email: info@ryezone.com
    maintainer_keyid: C88D9E585E3018CAC18A5396F6C4E6A506940F5F
    apt_repo_base_directory: /opt/apt_repo
    apt_repo_owner: esten
    distributions:
      - Origin: apt.ryezone.com
        Label: Local Apt Repository
        Codename: focal
        Architectures:
          - amd64
          - source
        Components:
          - main
        Description: Ryezone Labs Ubuntu Package Repo
        SignWith: "{{ maintainer_keyid }}"
        Log: /opt/apt_repo/apt.ryezone.com.log
      - Origin: ubuntu-focal
        Label: Ubuntu Focal Mirror
        Codename: ubuntu-focal
        Description: Ubuntu 20.04 Focal Mirror
        Architectures:
          - amd64
          - source
        Components:
          - main
          - restricted
          - universe
          - multiverse
        SignWith: "{{ maintainer_keyid }}"
        Update: ubuntu-focal
        Log: /opt/apt_repo/ubuntu-focal.log
      - Origin: Saltstack
        Label: Saltstack
        Suite: buster-saltstack
        Codename: buster-saltstack
        Description: Saltstack nightly packages for wheezy
        Architectures:
          - amd64
          - source
        Components:
          - main
        SignWith: "{{ maintainer_keyid }}"
        Update: buster-saltstack
        Log: /opt/apt_repo/buster-saltstack.log
    updates:
      - Name: buster-saltstack
        Method: https://repo.saltproject.io/py3/debian/10/amd64/latest
        Suite: buster
        Components:
          - main
        Architectures:
          - amd64
          - source
        VerifyRelease: 0E08A149DE57BFBE
      - Name: ubuntu-focal
        Method: http://us.archive.ubuntu.com/ubuntu/
        Suite: focal
        Components:
          - main
          - restricted
          - universe
          - multiverse
        Architectures:
          - amd64
          - source
        VerifyRelease: 871920D1991BC93C
    options:
      basedir: /opt/apt_repo
      # gnupghome: /opt/apt_repo/.gnupg
      keepunreferencedfiles: true
    trusted_keys:
      - name: salt-archive-keyring.gpg
        url: https://repo.saltproject.io/py3/debian/10/amd64/latest/salt-archive-keyring.gpg
  tasks:
    - name: Install apt packaging tools
      ansible.builtin.package:
        name:
          - dpkg-dev
          - dpkg-sig
          - reprepro
      become: yes
      tags:
        install-packages

    - name: Create Repo Directory Structures
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0755
        owner: "{{ apt_repo_owner }}"
      become: true
      loop:
        - "{{ apt_repo_base_directory }}"
        - "{{ apt_repo_base_directory }}/conf"
        - "{{ apt_repo_base_directory }}/conf/distributions"
        # - "{{ apt_repo_base_directory }}/conf/options"
      tags:
        - create-repo-base-directory

    - name: Create Repo Directory Structures
      ansible.builtin.file:
        path: "{{ apt_repo_base_directory }}/conf/updates"
        state: directory
        mode: 0755
        owner: "{{ apt_repo_owner }}"
      become: true
      when:
        - updates is defined
        - updates | length > 0
      tags:
        - create-repo-base-directory

    - name: Export GPG Public Key
      ansible.builtin.shell:
        cmd: gpg --armor --export {{ maintainer_keyid }} > {{ apt_repo_base_directory }}/apt.ryezone.com.key
        warn: false
        creates: "{{ apt_repo_base_directory }}/apt.ryezone.com.key"

    - name: Create Distribution Config
      ansible.builtin.template:
        src: templates/distributions.conf.j2
        dest: "{{ apt_repo_base_directory }}/conf/distributions/{{ distribution.Origin }}.conf"
      loop: "{{ distributions }}"
      loop_control:
        loop_var: distribution

    - name: Create Updates Config
      ansible.builtin.template:
        src: templates/updates.conf.j2
        dest: "{{ apt_repo_base_directory }}/conf/updates/{{ update.Name }}.conf"
      loop: "{{ updates }}"
      loop_control:
        loop_var: update

    - name: Create Options Config
      ansible.builtin.template:
        src: templates/options.conf.j2
        dest: "{{ apt_repo_base_directory }}/conf/options"
      when:
        - options is defined

    - name: Download Keys
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: /tmp/{{ item.name }}.gpg
      loop: "{{ trusted_keys }}"

    - name: Import Keys
      ansible.builtin.command:
        argv:
          - gpg
          - --import
          - /tmp/{{ item.name }}.gpg
      loop: "{{ trusted_keys }}"

    - name: Import Ubuntu archive key
      ansible.builtin.command:
        argv:
          - gpg
          - --import
          - /usr/share/keyrings/ubuntu-archive-keyring.gpg
