- name: Add chart repos.
  community.kubernetes.helm_repository:
    name: "{{ metallb.helm.repo_name }}"
    repo_url: "{{ metallb.helm.repo_url }}"
  tags:
    - metallb

- name: Update Helm Repositories
  ansible.builtin.command: helm repo update
  changed_when: false
  tags:
    - metallb

- name: Deploy metallb chart
  community.kubernetes.helm:
    name: "{{ metallb.helm.chart_name }}"
    chart_ref: "{{ metallb.helm.repo_name }}/{{ metallb.helm.chart_name }}"
    chart_version: "{{ metallb.helm.chart_version }}"
    release_namespace: "{{ metallb.helm.namespace }}"
    create_namespace: true
    kubeconfig: "{{ kube_config_file }}"
    values: "{{ metallb_values }}"
