- hosts: localhost
  connection: local
  tasks:
    - name: apply terraform plan
      ansible.builtin.command:
        argv:
          - terraform
          - apply
          - -no-color
          - -json
          - tf.plan
      environment:
        ARM_CLIENT_ID: "{{ azure_service_principal.appId }}"
        ARM_CLIENT_SECRET: "{{ azure_service_principal.password }}"
        ARM_SUBSCRIPTION_ID: "{{ azure_service_principal.subscriptionId }}"
        ARM_TENANT_ID: "{{ azure_service_principal.tenantId }}"
