USE master;
GO
IF DB_ID (N'vault') IS NULL
CREATE DATABASE [vault]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'vault', FILENAME = N'/var/opt/mssql/data/vault-db.mdb' , SIZE = 131072KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'vault_log', FILENAME = N'/var/opt/mssql/data/vault-db.ldb' , SIZE = 131072KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [vault] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [vault] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [vault] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [vault] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [vault] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [vault] SET ARITHABORT OFF 
GO
ALTER DATABASE [vault] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [vault] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [vault] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [vault] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [vault] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [vault] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [vault] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [vault] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [vault] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [vault] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [vault] SET  DISABLE_BROKER 
GO
ALTER DATABASE [vault] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [vault] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [vault] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [vault] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [vault] SET  READ_WRITE 
GO
ALTER DATABASE [vault] SET RECOVERY FULL 
GO
ALTER DATABASE [vault] SET  MULTI_USER 
GO
ALTER DATABASE [vault] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [vault] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [vault] SET DELAYED_DURABILITY = DISABLED 
GO
USE [vault]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [vault]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [vault] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
GO
-- Verify the database files and sizes
SELECT name, size, size*1.0/128 AS [Size in MBs]
FROM sys.master_files
WHERE name = N'vault';
GO