- name: Build Custom Ubuntu Autoinstall ISO
  ansible.builtin.import_playbook: /ansible/playbooks/customize-iso-uefi.yml
  tags:
    - iso

- name: Build cidata ISOs
  ansible.builtin.import_playbook: /ansible/playbooks/cidata-iso.yml
  tags:
    - cidata

# TODO: Separate this into a separate docker image
# Reasoning:
#  - Separates concerns of building ISOs from concerns of building VM Templates
#  - Reduces complexity of docker images.
#  - Makes maintenance of packer process lighter.
#  - Eliminates need for proxmox credentials when generating ISOs

- name: Build Packer HCL Files
  ansible.builtin.import_playbook: /ansible/playbooks/packer-hcl.yml
  tags:
    - packer

- name: Upload Proxmox ISO files
  ansible.builtin.import_playbook: /ansible/playbooks/upload-proxmox-iso.yml
  tags:
    - proxmox_upload
