- name: install Postgres package
  ansible.builtin.package:
    name:
      - acl
      - postgresql
  become: true

- name: Enable and Start postgres
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true
  become: true

- name: Install pip
  ansible.builtin.package:
    name: python3-pip
  become: true

- name: Install python support libraries
  ansible.builtin.pip:
    name: psycopg2-binary
  become: true

- name: Create Databases
  community.postgresql.postgresql_db:
    name: "{{ db.name }}"
  become: true
  become_user: postgres
  loop_control:
    loop_var: db
    label: "{{ db.name }}"
  loop: "{{ postgres_databases }}"

- name: Connect to each database and create database owner user
  community.postgresql.postgresql_user:
    db: "{{ db.name }}"
    user: "{{ db.owner_username }}"
    password: "{{ db.owner_password }}"
  become: true
  become_user: postgres
  loop_control:
    loop_var: db
    label: "{{ db.name }} ==> {{ db.owner_username }}"
  loop: "{{ postgres_databases }}"

- name: Grant all privileges to database owner user
  community.postgresql.postgresql_privs:
    database: "{{ db.name }}"
    privs: ALL
    type: database
    roles: "{{ db.owner_username }}"
  become: true
  become_user: postgres
  loop_control:
    loop_var: db
    label: "{{ db.name }} ==> {{ db.owner_username }}"
  loop: "{{ postgres_databases }}"

