tools_server:
  hosts:
    tools.rye.ninja:
      ansible_host: 10.5.7.10
      ansible_user: automation-user
      #TODO: Pull auth_pass and virtual_router_id from 1Password
      keepalived_auth_pass: 346728
      keepalived_virtual_router_id: 141
      keepalived_vip: 10.5.7.2/16
      keepalived_interface: enp2s0.61
      httpd_modules:
        - proxy
        - proxy_http
        - remoteip
        - headers
      httpd_sites_enabled:
        - site: 000-default.conf
          host: tools.rye.ninja
          documentRoot: /var/www/html
        - site: 100-apt-mirror.conf
          host: apt.tools.rye.ninja
          documentRoot: /var/lib/apt-mirror/www
          directories:
            - path: /var/lib/apt-mirror/www
              options: Indexes followSymLinks
              allowOverride: None
              require: all granted
        - site: 100-pxe-mirror.conf
          host: pxe.tools.rye.ninja
          locations:
            - path: /tftp
              proxyPass: '!'
          aliases:
            - path: /tftp
              dest: /var/lib/pxeroot
          directories:
            - path: /var/lib/pxeroot
              options: Indexes followSymLinks
              allowOverride: None
              require: all granted
          proxyPreserveHost: true
          requestHeaders:
            - set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
          proxyPass:
            - from: /
              to: http://127.0.0.1:30083/
          proxyPassReverse:
            - from: /
              to: http://127.0.0.1:30083/
        - site: 101-netbox.conf
          host: netbox.tools.rye.ninja
          directories:
            - path: /opt/netbox/netbox/static
              options: Indexes FollowSymLinks MultiViews
              allowOverride: None
              require: all granted
          locations:
            - path: /static
              proxyPass: '!'
          aliases:
            - path: /static
              dest: /opt/netbox/netbox/static
          proxyPreserveHost: true
          requestHeader: set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
          proxyPass:
            - from: /
              to: http://127.0.0.1:8001/
          proxyPassReverse:
            - from: /
              to: http://127.0.0.1:8001/
        - site: 102-pihole.conf
          host: pihole.tools.rye.ninja
          proxyPreserveHost: true
          requestHeaders:
            - set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
          proxyPass:
            - from: /
              to: http://127.0.0.1:30085/
          proxyPassReverse:
            - from: /
              to: http://127.0.0.1:30085/

      postgres_databases:
        - name: netbox
          owner_username: dbo_netbox
          owner_password: "{{ netbox_dbo_password | default(lookup('ansible.builtin.password', 'tmp/netbox_dbo_password chars=ascii_letters,digits length=50')) }}"
        - name: smallstep
          owner_username: dbo_smallstep
          owner_password: "{{ smallstep_dbo_password | default(lookup('ansible.builtin.password', 'tmp/smallstep_dbo_password chars=ascii_letters,digits length=50')) }}"
      netbox_allowed_hosts:
        - netbox.tools.rye.ninja
        - 127.0.0.1
        - localhost
      netbox_db_username: dbo_netbox
      netbox_db_password: "{{ netbox_dbo_password | default(lookup('ansible.builtin.password', 'tmp/netbox_dbo_password chars=ascii_letters,digits length=50')) }}"
      netbox_secret_key: "{{ netbox_secret_key_value | default(lookup('ansible.builtin.password', 'tmp/netbox_secret_key chars=ascii_letters,digits length=60')) }}"
      netbox_metrics_enabled: true
      netbox_enable_napalm: true
      nitrokey_hsm_label: lab-hsm
      # nitrokey_hsm_init_status_override: true
      nitrokey_hsm_keys_to_generate:
        - label: smallstep_root_certificate
          key_type: rsa:2048
        - label: gnupg_local_apt_root_keypair
          key_type: rsa:2048
      nitrokey_hsm_gpg_certs_to_generate:
        - label: gnupg_local_apt_root_keypair
          cn: Esten Rye
      nitrokey_hsm_export_certificates: false
      pihole_web_password: "{{ pihole_web_password_value | default(lookup('ansible.builtin.password', 'tmp/pihole_web_password chars=ascii_letters,digits length=32')) }}"
      pihole_ipv4_address: 10.5.7.2
      shoelaces_network_maps:
        - network: 10.5.11.1/32
          script:
            name: ubuntu.ipxe
            params:
              release: 20.04.5
              bios_type: bios
              hostname: zbox-01.usmnblm01.rye.ninja
              password_hash: "{{ default_automation_user_passwordhash | urlencode }}"
        - network: 10.5.11.2/32
          script:
            name: talos.ipxe
            params:
              arch: amd64
              hostname: zbox-02.usmnblm01.rye.ninja
              node_type: controlplane
              talos_secrets:
                k8s:
                  clusterName: k8s-bare-metal
                  hostname: k8s-bare-metal.usmnblm01.rye.ninja
                  port: '6443'
                cluster:
                    id: "{{ bare_metal_talos_secrets.cluster.id | urlencode }}"
                    secret: "{{ bare_metal_talos_secrets.cluster.secret | urlencode }}"
                secrets:
                    bootstraptoken: "{{ bare_metal_talos_secrets.secrets.bootstraptoken | urlencode }}"
                    aescbcencryptionsecret: "{{ bare_metal_talos_secrets.secrets.aescbcencryptionsecret | urlencode }}"
                trustdinfo:
                    token: "{{ bare_metal_talos_secrets.trustdinfo.token | urlencode }}"
                certs:
                    etcd:
                        crt: "{{ bare_metal_talos_secrets.certs.etcd.crt | urlencode }}"
                        key: "{{ bare_metal_talos_secrets.certs.etcd.key | urlencode }}"
                    k8s:
                        crt: "{{ bare_metal_talos_secrets.certs.k8s.crt | urlencode }}"
                        key: "{{ bare_metal_talos_secrets.certs.k8s.key | urlencode }}"
                    k8saggregator:
                        crt: "{{ bare_metal_talos_secrets.certs.k8saggregator.crt | urlencode }}"
                        key: "{{ bare_metal_talos_secrets.certs.k8saggregator.key | urlencode }}"
                    k8sserviceaccount:
                        key: "{{ bare_metal_talos_secrets.certs.k8sserviceaccount.key | urlencode }}"
                    os:
                        crt: "{{ bare_metal_talos_secrets.certs.os.crt | urlencode }}"
                        key: "{{ bare_metal_talos_secrets.certs.os.key | urlencode }}"
        - network: 10.5.255.101/32
          script:
            name: talos.ipxe
            params:
              arch: amd64
              hostname: macbook
              node_type: controlplane
              talos_secrets:
                k8s:
                  clusterName: foo
                  hostname: foo.rye.ninja
                  port: '6443'
                cluster:
                    id: "{{ bare_metal_talos_secrets.cluster.id | urlencode }}"
                    secret: "{{ bare_metal_talos_secrets.cluster.secret | urlencode }}"
                secrets:
                    bootstraptoken: "{{ bare_metal_talos_secrets.secrets.bootstraptoken | urlencode }}"
                    aescbcencryptionsecret: "{{ bare_metal_talos_secrets.secrets.aescbcencryptionsecret | urlencode }}"
                trustdinfo:
                    token: "{{ bare_metal_talos_secrets.trustdinfo.token | urlencode }}"
                certs:
                    etcd:
                        crt: "{{ bare_metal_talos_secrets.certs.etcd.crt | urlencode }}"
                        key: "{{ bare_metal_talos_secrets.certs.etcd.key | urlencode }}"
                    k8s:
                        crt: "{{ bare_metal_talos_secrets.certs.k8s.crt | urlencode }}"
                        key: "{{ bare_metal_talos_secrets.certs.k8s.key | urlencode }}"
                    k8saggregator:
                        crt: "{{ bare_metal_talos_secrets.certs.k8saggregator.crt | urlencode }}"
                        key: "{{ bare_metal_talos_secrets.certs.k8saggregator.key | urlencode }}"
                    k8sserviceaccount:
                        key: "{{ bare_metal_talos_secrets.certs.k8sserviceaccount.key | urlencode }}"
                    os:
                        crt: "{{ bare_metal_talos_secrets.certs.os.crt | urlencode }}"
                        key: "{{ bare_metal_talos_secrets.certs.os.key | urlencode }}"

