tools_server:
  hosts:
    tools.rye.ninja:
      ansible_host: 10.5.7.10
      ansible_user: automation-user
      #TODO: Pull auth_pass and virtual_router_id from 1Password
      keepalived_auth_pass: 346728
      keepalived_virtual_router_id: 141
      keepalived_vip: 10.5.7.2/16
      keepalived_interface: enp2s0.61
      httpd_modules:
        - proxy
        - proxy_http
        - remoteip
        - headers
      httpd_sites_enabled:
        - site: 000-default.conf
          host: tools.rye.ninja
          documentRoot: /var/www/html
        - site: 100-apt-mirror.conf
          host: apt.tools.rye.ninja
          documentRoot: /var/lib/apt-mirror/www
          directories:
            - path: /var/lib/apt-mirror/www
              options: Indexes followSymLinks
              allowOverride: None
              require: all granted
        - site: 100-pxe-mirror.conf
          host: pxe.tools.rye.ninja
          locations:
            - path: /tftp
              proxyPass: '!'
          aliases:
            - path: /tftp
              dest: /var/lib/pxeroot
          directories:
            - path: /var/lib/pxeroot
              options: Indexes followSymLinks
              allowOverride: None
              require: all granted
          proxyPreserveHost: true
          requestHeaders:
            - set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
          proxyPass:
            - from: /
              to: http://127.0.0.1:30083/
          proxyPassReverse:
            - from: /
              to: http://127.0.0.1:30083/
        - site: 101-netbox.conf
          host: netbox.tools.rye.ninja
          directories:
            - path: /opt/netbox/netbox/static
              options: Indexes FollowSymLinks MultiViews
              allowOverride: None
              require: all granted
          locations:
            - path: /static
              proxyPass: '!'
          aliases:
            - path: /static
              dest: /opt/netbox/netbox/static
          proxyPreserveHost: true
          requestHeader: set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
          proxyPass:
            - from: /
              to: http://127.0.0.1:8001/
          proxyPassReverse:
            - from: /
              to: http://127.0.0.1:8001/
        - site: 102-pihole.conf
          host: pihole.tools.rye.ninja
          proxyPreserveHost: true
          requestHeaders:
            - set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
          proxyPass:
            - from: /
              to: http://127.0.0.1:30085/
          proxyPassReverse:
            - from: /
              to: http://127.0.0.1:30085/

      postgres_databases:
        - name: netbox
          owner_username: dbo_netbox
          owner_password: "{{ netbox_dbo_password | default(lookup('ansible.builtin.password', 'tmp/netbox_dbo_password chars=ascii_letters,digits length=50')) }}"
        - name: smallstep
          owner_username: dbo_smallstep
          owner_password: "{{ smallstep_dbo_password | default(lookup('ansible.builtin.password', 'tmp/smallstep_dbo_password chars=ascii_letters,digits length=50')) }}"
      netbox_allowed_hosts:
        - netbox.tools.rye.ninja
        - 127.0.0.1
        - localhost
      netbox_db_username: dbo_netbox
      netbox_db_password: "{{ netbox_dbo_password | default(lookup('ansible.builtin.password', 'tmp/netbox_dbo_password chars=ascii_letters,digits length=50')) }}"
      netbox_secret_key: "{{ netbox_secret_key_value | default(lookup('ansible.builtin.password', 'tmp/netbox_secret_key chars=ascii_letters,digits length=60')) }}"
      netbox_metrics_enabled: true
      netbox_enable_napalm: true
      nitrokey_hsm_label: lab-hsm
      # nitrokey_hsm_init_status_override: true
      nitrokey_hsm_keys_to_generate:
        - label: smallstep_root_certificate
          key_type: rsa:2048
        - label: gnupg_local_apt_root_keypair
          key_type: rsa:2048
      nitrokey_hsm_gpg_certs_to_generate:
        - label: gnupg_local_apt_root_keypair
          cn: Esten Rye
      nitrokey_hsm_export_certificates: false
      pihole_web_password: "{{ pihole_web_password_value | default(lookup('ansible.builtin.password', 'tmp/pihole_web_password chars=ascii_letters,digits length=32')) }}"
      pihole_ipv4_address: 10.5.7.2
      shoelaces_network_maps:
        # - network: 10.5.11.4/29
        #   script:
        #     name: ubuntu.ipxe
        #     params:
        #       bios_type: bios
        #       release: 20.04.5
        #       password_hash: $6$automation-user$KJJd3iL8sCfkc4YTLOqDAQYnmMj/2VPKZxScl8sDeWZ2VcdoXEJHrAo.VGEVSP8h550ma6ok3NTss7i9elMVP/
        - network: 10.5.11.0/30
          script:
            name: talos.ipxe
            params:
              arch: amd64
              node_type: controlplane
              machine_type: zbox-ci320
              mac_address_pattern: 00:01:2e:*
              ip_address_prefix: 16
              gateway_ip_address: 10.5.0.1
              vip_address: 10.5.11.0
              talos_secrets: "{{ bare_metal_talos_secrets }}"
        - network: 10.5.11.4/30
          script:
            name: talos.ipxe
            params:
              arch: amd64
              node_type: worker
              machine_type: zbox-ci320
              mac_address_pattern: 00:01:2e:*
              ip_address_prefix: 16
              gateway_ip_address: 10.5.0.1
              vip_address: 10.5.11.0
              talos_secrets: "{{ bare_metal_talos_secrets }}"
        - network: 10.5.11.16/32
          script:
            name: talos.ipxe
            params:
              arch: amd64
              node_type: worker
              machine_type: dell-r610
              install_disk_size: <=1TB
              eth0_mac_address: f0:4d:a2:0b:fd:f4
              eth1_mac_address: f0:4d:a2:0b:fd:f6
              eth2_mac_address: f0:4d:a2:0b:fd:f8
              eth3_mac_address: f0:4d:a2:0b:fd:fa
              ip_address_bond: 10.5.11.17
              ip_address_prefix: 16
              gateway_ip_address: 10.5.0.1
              vip_address: 10.5.11.0
              talos_secrets: "{{ bare_metal_talos_secrets }}"
        - network: 10.5.11.18/32
          script:
            name: talos.ipxe
            params:
              arch: amd64
              node_type: worker
              machine_type: dell-r610
              install_disk_size: <=1TB
              eth0_mac_address: 00:21:9b:99:3d:c7
              eth1_mac_address: 00:21:9b:99:3d:c9
              eth2_mac_address: 00:21:9b:99:3d:cb
              eth3_mac_address: 00:21:9b:99:3d:cd
              ip_address_bond: 10.5.11.19
              ip_address_prefix: 16
              gateway_ip_address: 10.5.0.1
              vip_address: 10.5.11.0
              talos_secrets: "{{ bare_metal_talos_secrets }}"
