tools_server:
  hosts:
    tools.rye.ninja:
      ansible_host: 10.5.7.10
      ansible_user: automation-user
      #TODO: Pull auth_pass and virtual_router_id from 1Password
      keepalived_auth_pass: 346728
      keepalived_virtual_router_id: 141
      keepalived_vip: 10.5.7.2/16
      keepalived_interface: enp2s0.61
      httpd_modules:
        - proxy
        - proxy_http
        - headers
      httpd_sites_enabled:
        - site: 000-default.conf
          port: "{{ httpd_http_port }}"
          documentRoot: /var/www/html
        - site: 100-apt-mirror.conf
          port: 30081
          documentRoot: /var/lib/apt-mirror/www
          directory:
            path: /var/lib/apt-mirror/www
            options: Indexes followSymLinks
            allowOverride: None
            require: all granted
        - site: 101-netbox.conf
          port: 30082
          directory:
            path: /opt/netbox/netbox/static
            options: Indexes FollowSymLinks MultiViews
            allowOverride: None
            require: all granted
          locations:
            - path: /static
              proxyPass: '!'
          aliases:
            - path: /static
              dest: /opt/netbox/netbox/static
          proxyPreserveHost: true
          requestHeader: set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
          proxyPass:
            - from: /
              to: http://127.0.0.1:8001/
          proxyPassReverse:
            - from: /
              to: http://127.0.0.1:8001/
      postgres_databases:
        - name: netbox
          owner_username: dbo_netbox
          owner_password: "{{ netbox_dbo_password | default(lookup('ansible.builtin.password', 'tmp/netbox_dbo_password chars=ascii_letters,digits length=50')) }}"
        - name: smallstep
          owner_username: dbo_smallstep
          owner_password: "{{ smallstep_dbo_password | default(lookup('ansible.builtin.password', 'tmp/smallstep_dbo_password chars=ascii_letters,digits length=50')) }}"
      netbox_allowed_hosts:
        - netbox.tools.rye.ninja
        - 127.0.0.1
        - localhost
      netbox_db_username: dbo_netbox
      netbox_db_password: "{{ netbox_dbo_password | default(lookup('ansible.builtin.password', 'tmp/netbox_dbo_password chars=ascii_letters,digits length=50')) }}"
      netbox_secret_key: "{{ netbox_secret_key_value | default(lookup('ansible.builtin.password', 'tmp/netbox_secret_key chars=ascii_letters,digits length=60')) }}"
      netbox_metrics_enabled: true
      netbox_enable_napalm: true
      nitrokey_hsm_label: lab-hsm
      # nitrokey_hsm_init_status_override: true
      nitrokey_hsm_keys_to_generate:
        - label: smallstep_root_certificate
          key_type: rsa:2048
      nitrokey_hsm_export_certificates: false
      pihole_web_password: "{{ pihole_web_password_value | default(lookup('ansible.builtin.password', 'tmp/pihole_web_password chars=ascii_letters,digits length=32')) }}"
      pihole_ipv4_address: 10.5.7.2
