- hosts: tools_server
  tasks:
    - name: ping the server
      ansible.builtin.ping:

    - name: update apt package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true
  roles:
    - keepalived
