- hosts: tools_server
  connection: local
  tasks:
    - ansible.builtin.debug:
        var: ansible_os_family
    - ansible.builtin.debug:
        var: ansible_architecture
  roles:
    - nitrokey_hsm_generate_certs
  tags:
    - hsm
    - smallstep
    - nitrokey_hsm_generate_certs
