deployer:
  hosts:
    # ryezone-labs-prod:
    #   truenas_backend: nas.ryezone.com
    #   truenas_trust_cert: true
    #   # truenas_dataset_root should be 15 chars or less
    #   truenas_dataset_root: main/k8s/prod
    #   truenas_iscsi_name_prefix: pf9-
    #   truenas_iscsi_name_suffix: -rzl-prod
    #   ingress_load_balancer_ip: "10.5.253.1"
    #   cluster_wildcard_tld: services.8825.rye.ninja
    #   pihole:
    #     dns:
    #       load_balancer_ip: 10.5.253.53
    #       annotations:
    #         metallb.universe.tf/allow-shared-ip: pihole-svc
    #     dhcp:
    #       load_balancer_ip: 10.5.253.53
    #       annotations:
    #         metallb.universe.tf/allow-shared-ip: pihole-svc

    services:
      target: aws
      ingress_load_balancer_ip: ""
      cluster_wildcard_tld: services.rye.ninja
      pihole:
        dns:
          load_balancer_ip: ""
          annotations: {}
        dhcp:
          load_balancer_ip: ""
          annotations: {}

controlplane:
  hosts:
    pf9-ryezone-labs-prod-node01.ryezone.com:
    pf9-ryezone-labs-prod-node02.ryezone.com:
    pf9-ryezone-labs-prod-node03.ryezone.com:

worker:
  hosts:
    pf9-ryezone-labs-prod-node04.ryezone.com:
    pf9-ryezone-labs-prod-node05.ryezone.com:
    pf9-ryezone-labs-prod-node06.ryezone.com:

cluster:
  children:
    controlplane:
    worker:
  vars:
    pf9_prep_node: true
