deployer:
  hosts:
    default:

controlplane:
  hosts:
    pf9-ryezone-labs-prod-node01.ryezone.com:
    pf9-ryezone-labs-prod-node02.ryezone.com:
    pf9-ryezone-labs-prod-node03.ryezone.com:

worker:
  hosts:
    pf9-ryezone-labs-prod-node04.ryezone.com:
    pf9-ryezone-labs-prod-node05.ryezone.com:
    pf9-ryezone-labs-prod-node06.ryezone.com:

cluster:
  children:
    controlplane:
    worker:
