---
- name: restart multipath-tools
  ansible.builtin.service:
    name: multipath-tools
    state: restarted
  become: true

- name: restart rke2-{{ node_type }}
  ansible.builtin.systemd:
    name: rke2-{{ node_type }}
    state: restarted
  become: true
