apiVersion: batch/v1
kind: Job
metadata:
  name: clone-olla-hallengren-sp
  namespace: mssql
spec:
  template:
    spec:
      containers:
      - name: sqlcmd
        image: estenrye/mssql-tools
        command:
          - /bin/bash
          - /entrypoint.sh
          - /sql/select-version.sql
        env:
          - name: SQL_SERVER_HOSTNAME
            value: primary-mssql-server.mssql.svc.cluster.local
          - name: SQL_SERVER_LOGIN
            value: sa
          - name: SQL_SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: primary-mssql-server
                key: sa_password
      restartPolicy: Never
  backoffLimit: 4

