cloudflare:
  zone: example.com
platform_environment: "dev"
kubernetes_zone: "{{ platform_environment }}.{{ cloudflare.zone }}"
mgmt_fqdn: kube-api.{{ kubernetes_zone }}
join_token: totallynotmytoken
is_initial_node: false
is_agent_node: false
taint_server_nodes: false
node_type: "{% if is_agent_node %}agent{% else %}server{% endif %}"
node_ready_timeout: 3
node_name: "{{ inventory_hostname }}.{{ kubernetes_zone }}"

install_rke2_channel: latest
install_rke2_type: "{% if is_agent_node %}agent{% else %}server{% endif %}"
install_rke2_version: v1.19.9+rke2r1

rke2_ingress_nginx_controller_metrics_enabled: false
rke2_ingress_nginx_controller_metrics_serviceMonitor_enabled: false
rke2_ingress_nginx_service_external_dns_hostname: "{{ kubernetes_zone }}"
rke2_ingress_nginx_service_external_dns_ttl: "120"
rke2_ingress_nginx_service_external_dns_cloudflare_proxied: false
rke2_enable_nfs_csi: true
rke2_enable_iscsi_csi: true
