mgmt_fqdn: rke2.lab.bradlab.tech
mgmt_vip: 192.168.30.200
join_token: totallynotmytoken
enable_kube_karp: false
is_initial_node: false
is_agent_node: false
taint_server_nodes: false
node_type: "{% if is_agent_node %}agent{% else %}server{% endif %}"
node_ready_timeout: 5

install_rke2_channel: latest
install_rke2_type: "{% if is_agent_node %}agent{% else %}server{% endif %}"
install_rke2_version: v1.20.5+rke2r1

rke2_ingress_nginx_controller_metrics_enabled: false
rke2_ingress_nginx_controller_metrics_serviceMonitor_enabled: false
rke2_ingress_nginx_service_external_dns_hostname: "{{ kubernetes_zone }}"
rke2_ingress_nginx_service_external_dns_ttl: "120"
rke2_ingress_nginx_service_external_dns_cloudflare_proxied: false