audit_policy_path: /var/opt/pf9/kube/apiserver-config/audit-policy.yaml
audit_policy_owner: pf9
audit_policy_group: pf9group

audit_policy:
  apiVersion: audit.k8s.io/v1
  kind: Policy
  rules:
    # A catch-all rule to log all requests that modify state at the Request level.
    - level: Request
      verbs:
        - create
        - delete
        - deletecollection
        - patch
        - update

    # A catch-all rule to log all other requests at the Metadata level.  (get, list, watch)
    - level: Metadata
      # Long-running requests like watches that fall under this rule will not
      # generate an audit event in RequestReceived.
      omitStages:
        - "RequestReceived"
