platform_environment: common
cluster_wildcard_vip: 10.5.15.1
cluster_vips:
  - cloudflare_value: "{{ cluster_wildcard_vip }}"
    cloudflare_record: kube-api.common
  - cloudflare_value: "{{ cluster_wildcard_vip }}"
    cloudflare_record: "*.common"
join_token: "{{ common_cluster.join_token }}"
keepalived_virtual_router_id: 50
keepalived_auth_pass: 42
nitrokey_hsm_label: lab_hsm
usb:
  node01.common.ryezone.com:
    node: "{{ proxmox_node | default('undefined') }}"
    vmid: "{{ proxmox_vmid | default('undefined') }}"
    usb0: host=1-3.1,usb3=1
  node02.common.ryezone.com:
    node: "{{ proxmox_node | default('undefined') }}"
    vmid: "{{ proxmox_vmid | default('undefined') }}"
    usb0: host=2-1,usb3=1
  node03.common.ryezone.com:
    node: "{{ proxmox_node | default('undefined') }}"
    vmid: "{{ proxmox_vmid | default('undefined') }}"
    usb0: host=5-1,usb3=1
