kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
  disableDefaultCNI: true
  apiServerPort: 6443
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: "10.96.0.1/12"
    podSubnet: "10.240.0.0/16"
  featureGates:
  apiServer:
    extraArgs:
      audit-log-path: /var/log/k8s-apiServer-audit.log
      audit-log-maxage: "30"
      audit-log-maxbackup: "10"
      audit-log-maxsize: "100"
      enable-admission-plugins: "AlwaysPullImages,EventRateLimit"
      kubelet-preferred-address-types: Hostname,InternalDNS,InternalIP,ExternalDNS,ExternalIP
      kubelet-certificate-authority: /etc/kubernetes/pki/ca.crt
      profiling: "false"
      tls-cipher-suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  controllerManager:
    extraArgs:
      profiling: "false"
      terminated-pod-gc-threshold: "100"
  scheduler:
    extraArgs:
      profiling: "false"
  ---
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  rotateCertificates: true
  serverTLSBootstrap: true
nodes:
  - role: control-plane
  # - role: control-plane
  # - role: control-plane
  # - role: worker
  #   extraPortMappings:
  #   - containerPort: 32080
  #     hostPort: 10080
  #   - containerPort: 32443
  #     hostPort: 10443
  # - role: worker
  #   extraPortMappings:
  #   - containerPort: 32080
  #     hostPort: 20080
  #   - containerPort: 32443
  #     hostPort: 20443
  - role: worker
    extraPortMappings:
    - containerPort: 32080
      hostPort: 30080
    - containerPort: 32443
      hostPort: 30443
