---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - group_vars/all.yml
  tasks:
  - name: Set A Records
    community.general.cloudflare_dns:
      zone: "{{ cloudflare.zone }}"
      api_token: "{{ cloudflare.api_token }}"
      type: A
      value: "{{ item.value }}"
      record: "{{ item.record }}.{{ platform_environment }}"
      state: present
    loop:
      - record: haproxy01
        value: 10.5.99.18
      - record: haproxy02
        value: 10.5.99.19
      - record: kube-api
        value: 10.5.99.20
      - record: controlplane01
        value: 10.5.99.21
      - record: controlplane02
        value: 10.5.99.22
      - record: controlplane03
        value: 10.5.99.23
      - record: node01
        value: 10.5.99.31
      - record: node02
        value: 10.5.99.32
      - record: node03
        value: 10.5.99.33
