---
- hosts: external_load_balancer
  roles:
    - haproxy
    - keepalived

- hosts: kubernetes_cluster
  roles:
    - kubernetes

- hosts:
    - initial_controlplane
  roles:
    - kubernetes_cluster_node

- hosts:
    - additional_controlplane
  serial: 1
  roles:
    - kubernetes_cluster_node

- hosts:
    - nodes
  roles:
    - kubernetes_cluster_node
