- hosts: 127.0.0.1
  connection: local
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
      community.crypto.openssl_privatekey:
        path: files/secrets/acme_issuer_key.pem
        state: present
        return_content: true
      register: acme_issuer_key
    - name: generate value file for acmeCloudflareIssuer Helm Chart
      ansible.builtin.template:
        src: templates/acme_issuer_key.yml.j2
        dest: files/secrets/acme_issuer_key.yml

    - name: Add chart repos
      community.kubernetes.helm_repository:
        name: "{{ item.name }}"
        repo_url: "{{ item.repo_url }}"
      loop:
        - name: prometheus-community
          repo_url: https://prometheus-community.github.io/helm-charts
        - name: ingress-nginx
          repo_url: https://kubernetes.github.io/ingress-nginx
        - name: jetstack
          repo_url: https://charts.jetstack.io
        - name: kubernetes-dashboard
          repo_url: https://kubernetes.github.io/dashboard/
        - name: tremolo
          repo_url: https://nexus.tremolo.io/repository/helm/
        # - name: linkerd-stable
        #   repo_url: https://helm.linkerd.io/stable

    - name: Deploy Prometheus chart inside monitoring namespace (and create it)
      community.kubernetes.helm:
        name: kube-prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        chart_version: "{{ helm_chart_version_prometheus }}"
        release_namespace: monitoring
        create_namespace: true
    
    - name: Deploy NGINX Ingress Controller chart inside monitoring namespace (and create it)
      community.kubernetes.helm:
        name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        chart_version: "{{ helm_chart_version_ingress_nginx }}"
        release_namespace: ingress
        create_namespace: true
        values_files:
          - files/helm_values/ingress-nginx.yml

    - name: Deploy cert-manager chart inside cert-manager namespace (and create it)
      community.kubernetes.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        chart_version: "{{ helm_chart_version_cert_manager }}"
        release_namespace: cert-manager
        create_namespace: true
        values_files:
          - files/helm_values/cert-manager.yml

    - name: Deploy cert-manager configuration chart inside ingress namespace (and create it)
      community.kubernetes.helm:
        name: prod
        chart_ref: files/helm_charts/acmeCloudflareIssuer
        chart_version: 0.1.0
        release_namespace: "{{ item }}"
        create_namespace: true
        values_files:
          - files/secrets/acme_issuer_key.yml
        values:
          acmeUseProductionServer: true
      loop:
        - ingress
        - monitoring
        - kube-dashboard
        - openunison

    - name: Deploy ingress manifests in monitoring namespace (and create it)
      community.kubernetes.helm:
        name: ingress
        chart_ref: files/helm_charts/kubePrometheusStackIngress
        release_namespace: monitoring
        create_namespace: true
        values:
          zone: "{{ kubernetes_zone }}"

    - name: Deploy kube-dashboard chart in kube-dashboard namespace (and create it)
      community.kubernetes.helm:
        name: "{{ kubernetes_dashboard_release }}"
        chart_ref: kubernetes-dashboard/kubernetes-dashboard
        chart_version: "{{ helm_chart_version_kubernetes_dashboard }}"
        release_namespace: "{{ kubernetes_dashboard_namespace }}"
        create_namespace: true

    - name: Deploy ingress manifests in kube-dashboard namespace (and create it)
      community.kubernetes.helm:
        name: ingress
        chart_ref: files/helm_charts/kubeDashboardIngress
        release_namespace: "{{ kubernetes_dashboard_namespace }}"
        create_namespace: true
        values:
          zone: "{{ kubernetes_zone }}"

    - name: Deploy OpenUnison Operator chart inside openunison namespace (and create it)
      community.kubernetes.helm:
        name: openunison
        chart_ref: tremolo/openunison-operator
        chart_version: "{{ helm_chart_version_openunison }}"
        release_namespace: openunison
        create_namespace: true

    - name: Create OpenUnison secret
      community.kubernetes.k8s:
        state: present
        definition:
          apiVersion: v1
          type: Opaque
          metadata:
            name: orchestra-secrets-source
            namespace: openunison
          data:
            K8S_DB_SECRET: "{{ lookup('password', 'files/secrets/k8s_db_secret chars=ascii_letters,digits length=64') | b64encode }}"
            unisonKeystorePassword: "{{ lookup('password', 'files/secrets/unisonKeystorePassword chars=ascii_letters,digits length=256') | b64encode }}"
            OIDC_CLIENT_SECRET: "{{ lookup('password', 'files/secrets/oidc_client_secret chars=ascii_letters,digits length=8') | b64encode }}"
          kind: Secret

    - name: Deploy OpenUnison Operator chart inside openunison namespace (and create it)
      community.kubernetes.helm:
        name: orchestra
        chart_ref: tremolo/openunison-k8s-login-oidc
        chart_version: "{{ helm_chart_version_orchestra }}"
        release_namespace: openunison
        create_namespace: true
        values_files:
          - files/helm_values/orchestra.yml

    - name: Get a list of all service objects
      community.kubernetes.k8s_info:
        api_version: v1
        kind: Secret
        namespace: openunison
        name: ou-tls-certificate
      register: ou_ca
    - name: Get the api server config for oidc authentication
      community.kubernetes.k8s_info:
        api_version: v1
        kind: ConfigMap
        namespace: openunison
        name: api-server-config
      register: ou_api_config 
    - name: Write ou ca to localhost
      ansible.builtin.copy:
        content: '{{ ou_ca.resources[0].data["tls.crt"] | b64decode }}'
        dest: files/secrets/ou-ca.pem
    - name: Write config to localhost
      ansible.builtin.copy:
        content: "{{ ('- ' + ou_api_config.resources[0].data['oidc-api-server-flags']) | replace('\n', '\n- ') | indent(width=4, first=true)}}"
        dest: files/secrets/ou-config.yml
    - name: apply role bindings
      community.kubernetes.k8s:
        state: present
        src: "files/kubernetes_manifests/role_based_access_control/{{ item }}.yml"
      loop:
        - acl_okta_k8s_cluster_admin_dev

- hosts: controlplane
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: copy ou ca to controlplane
      ansible.builtin.copy:
        src: files/secrets/ou-ca.pem
        dest: /etc/kubernetes/pki/ou-ca.pem
      become: true
    - name: add oidc config to kube-apiserver manifest
      ansible.builtin.blockinfile:
        insertafter: "    - kube-apiserver"
        marker: "    # {mark}: ANSIBLE MANAGED BLOCK - OIDC FLAGS"
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
        block: "{{ lookup('file', 'files/secrets/ou-config.yml') }}"
      become: true

    # - name: Configure Cloudflare API Key for cert-manager
    #   community.kubernetes.k8s:
    #     state: present
    #     definition:
    #       apiVersion: v1
    #       kind: Secret
    #       metadata:
    #         name: cloudflare-api-token-secret
    #         namespace: cert-manager
    #       type: Opaque
    #       stringData:
    #         api-token: "{{ cert_manager_cloudflare_api_key }}"

    # - name: Configure LetsEncrypt Staging Issuer for cert-manager
    #   community.kubernetes.k8s:
    #     state: present
    #     definition:
    #       apiVersion: cert-manager.io/v1
    #       kind: ClusterIssuer
    #       metadata:
    #         name: letsencrypt-staging
    #         namespace: cert-manager
    #       spec:
    #         acme:
    #           email: "{{ cert_manager_cloudflare_account_email }}"
    #           server: https://acme-staging-v02.api.letsencrypt.org/directory
    #           preferredChain: "ISRG Root X1"
    #           privateKeySecretRef:
    #             name: letsencrypt-issuer-account-key
    #           solvers:
    #             - dns01:
    #                 cloudflare:
    #                   email: "{{ cert_manager_cloudflare_account_email }}"
    #                   apiKeySecretRef:
    #                     name: cloudflare-apikey-secret
    #                     key: apikey
    #               selector:
    #                 dnsZones:
    #                 - "{{ kubernetes_zone }}"
    #             - http01:
    #                 ingress:
    #                   class: nginx
    #                 selector:
    #                   matchLabels:
    #                     "use-http01-solver": "true"

    # - name: Deploy Linkerd chart inside linkerd namespace (and create it)
    #   community.kubernetes.helm:
    #     name: linkerd
    #     chart_ref: linkerd-stable/linkerd2
    #     chart_version: "{{ helm_chart_version_linkerd }}"
    #     release_namespace: linkerd
    #     create_namespace: true