---
- hosts: external_load_balancer
  roles:
    - haproxy
    - keepalived

- hosts: external_load_balancer
  tasks:
    - name: Drain api-server backend nodes.
      community.general.haproxy:
        state: drain
        host: "{{ item }}"
        backend: api-server
        socket: /var/run/haproxy.sock
      loop:
        - controlplane02
        - controlplane03
    - name: Drain node-join backend nodes.
      community.general.haproxy:
        state: drain
        host: "{{ item }}"
        backend: node-join
        socket: /var/run/haproxy.sock
      loop:
        - controlplane02
        - controlplane03
  become: true