---
- hosts: external_load_balancer
  roles:
    - haproxy
    - keepalived
  vars:
    haproxy_backends:
      - name: api-server
        mode: tcp
        port: 6443
        balance_method: roundrobin
        options:
          - httpchk GET /healthz
          - ssl-hello-chk
        http_checks:
          - expect status 200
        servers:
          - name: controlplane01
            address: "controlplane01.{{ kubernetes_zone }}"
          - name: controlplane02
            address: "controlplane02.{{ kubernetes_zone }}"
          - name: controlplane03
            address: "controlplane03.{{ kubernetes_zone }}"
      - name: node-join
        mode: tcp
        port: 9345
        check_options: check-ssl verify none
        balance_method: roundrobin
        options:
          - httpchk GET /ping
        http_checks:
          - expect status 200
        servers:
          - name: controlplane01
            address: "controlplane01.{{ kubernetes_zone }}"
          - name: controlplane02
            address: "controlplane02.{{ kubernetes_zone }}"
          - name: controlplane03
            address: "controlplane03.{{ kubernetes_zone }}"
      - name: http-ingress
        mode: tcp
        port: 80
        balance_method: roundrobin
        options:
          - httpchk GET /healthz
        http_checks:
          - expect status 200
        servers:
          - name: controlplane01
            address: "controlplane01.{{ kubernetes_zone }}"
          - name: controlplane02
            address: "controlplane02.{{ kubernetes_zone }}"
          - name: controlplane03
            address: "controlplane03.{{ kubernetes_zone }}"
      - name: https-ingress
        mode: tcp
        port: 443
        balance_method: roundrobin
        options:
          - httpchk GET /healthz
          - ssl-hello-chk
        http_checks:
          - expect status 200
        servers:
          - name: controlplane01
            address: "controlplane01.{{ kubernetes_zone }}"
          - name: controlplane02
            address: "controlplane02.{{ kubernetes_zone }}"
          - name: controlplane03
            address: "controlplane03.{{ kubernetes_zone }}"
    haproxy_frontends:
      - name: api-server
        bind_address: "*"
        bind_port: 6443
        mode: tcp
        default_backend: api-server
        options:
          - tcplog
      - name: node-join
        bind_address: "*"
        bind_port: 9345
        mode: tcp
        default_backend: node-join
        options:
          - tcplog
      - name: http-ingress
        bind_address: "*"
        bind_port: 80
        mode: tcp
        default_backend: http-ingress
        options:
          - tcplog
      - name: https-ingress
        bind_address: "*"
        bind_port: 443
        mode: tcp
        default_backend: https-ingress
        options:
          - tcplog

- hosts: external_load_balancer
  tasks:
    - name: Drain api-server backend nodes.
      community.general.haproxy:
        state: drain
        host: "{{ item }}"
        backend: api-server
        socket: /var/run/haproxy.sock
      loop:
        - controlplane02
        - controlplane03
    - name: Drain node-join backend nodes.
      community.general.haproxy:
        state: drain
        host: "{{ item }}"
        backend: node-join
        socket: /var/run/haproxy.sock
      loop:
        - controlplane02
        - controlplane03
  become: true