- hosts: additional_controlplane
  roles:
    - rke2
    - helm
  serial: 1
  vars:
    join_token: "{{ lookup('password', 'files/secrets/k8s_db_secret chars=ascii_letters,digits length=64') | b64encode }}"
    mgmt_vip: "{{ kubernetes_api_server_vip }}"
    mgmt_fqdn: "rke2.{{ kubernetes_zone }}"
    taint_server_nodes: not install_rancher
  become: true
- hosts: nodes
  roles:
    - rke2
  vars:
    join_token: "{{ lookup('password', 'files/secrets/k8s_db_secret chars=ascii_letters,digits length=64') | b64encode }}"
    mgmt_vip: "{{ kubernetes_api_server_vip }}"
    mgmt_fqdn: "rke2.{{ kubernetes_zone }}"
    is_agent_node: true
  become: true