collections:
  - name: ansible.posix
    version: 1.1.1
  - name: community.general
    version: 2.1.1
  - name: community.kubernetes
    version: 1.2.1
  - name: community.crypto
    version: 1.4.0
roles:
  - name: darkwizard242.cis_ubuntu_2004
    version: 1.0.2
