---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
  namespace: mssql-sql-ha
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
  loadBalancerIP: 10.5.253.2
