- name: configure apt hosted repos
  ansible.builtin.include_tasks:
    file: apt_hosted_repo.yml
  tags:
    - sonatype_nexus_configuration
    - sonatype_nexus_apt_hosted_repo

- name: configure apt proxy repos
  ansible.builtin.include_tasks:
    file: apt_proxy_repo.yml
  tags:
    - sonatype_nexus_configuration
    - sonatype_nexus_apt_proxy_repo

- name: configure raw hosted repos
  ansible.builtin.include_tasks:
    file: raw_hosted_repo.yml
  tags:
    - sonatype_nexus_configuration
    - sonatype_nexus_raw_hosted_repo
