debmirror_user_name: debmirror
debmirror_user_uid: 10000

debmirror_group_name: debmirror
debmirror_group_gid: 10000

debmirror_on_calendar: '*-*-* 00/6:30:00'
debmirror_accuracy_sec: 1m

debmirror_archive_keyring: /usr/share/keyrings/ubuntu-archive-keyring.gpg

mirror_dir: /var/lib/apt-mirror

mirror_repos:
  - remote:
      host: mirror.genesisadaptive.com
      root: ubuntu
    mirror:
      name: ubuntu
      dists:
        - focal
        - focal-backports
        - focal-security
        - focal-updates
      sections:
        - main
        - restricted
      arches:
        - amd64
        - i386
      rsync_extras:
        - trace
    state_cache_days: 0
    download:
      method: rsync
    output:
      verbose: true
  - remote:
      host: download.docker.com
      root: linux/ubuntu
      gpg_key: https://download.docker.com/linux/ubuntu/gpg
    mirror:
      name: docker
      dists:
        - focal
      sections:
        - stable
      arches:
        - amd64
    state_cache_days: 0
    download:
      method: http
    output:
      verbose: true
