debmirror_nginx_http_port: 80
debmirror_nginx_https_port: 443
debmirror_nginx_status_port: 8080
debmirror_nginx_tls_cert_path: /etc/nginx/pki/tls.crt
debmirror_nginx_tls_key_path: /etc/nginx/pki/tls.key
debmirror_nginx_user_uid: 10001
debmirror_nginx_group_gid: 10001

debmirror_user_name: debmirror
debmirror_user_uid: 10000

debmirror_group_name: debmirror
debmirror_group_gid: 10000


debmirror_on_calendar: '*-*-* 00/6:30:00'
debmirror_accuracy_sec: 1m

debmirror_archive_keyring: /usr/share/keyrings/ubuntu-archive-keyring.gpg

firewall_rules_allow_inbound_v4:
  - name: nginx http
    port: "{{ debmirror_nginx_http_port | int }}"
    protocol: tcp
  - name: nginx https
    port: "{{ debmirror_nginx_https_port | int }}"
    protocol: tcp
  - name: nginx status
    port: "{{ debmirror_nginx_status_port | int }}"
    protocol: tcp

firewall_rules_allow_outbound_v4: []

firewall_ipv6_enabled: false
firewall_rules_allow_inbound_v6: []
firewall_rules_allow_outbound_v6: []


mirror_dir: /var/lib/apt-mirror

mirror_repos:
  - remote:
      host: mirror.genesisadaptive.com
      root: ubuntu
    mirror:
      name: ubuntu
      dists:
        - focal
        - focal-backports
        - focal-security
        - focal-updates
      sections:
        - main
        - restricted
      arches:
        - amd64
        - i386
      rsync_extras:
        - trace
    state_cache_days: 0
    download:
      method: rsync
    output:
      verbose: true
    systemd:
      on_calendar: '*-*-* 01/6:30:00'
      accuracy_sec: 1m

  - remote:
      host: download.docker.com
      root: linux/ubuntu
      gpg_key: https://download.docker.com/linux/ubuntu/gpg
    mirror:
      name: docker
      dists:
        - focal
      sections:
        - stable
      arches:
        - amd64
    state_cache_days: 0
    download:
      method: http
    output:
      verbose: true

  # debmirror fails due to bug: https://bugs.launchpad.net/ubuntu/+source/debmirror/+bug/1702059
  # uses apt-mirror instead.
  - handler: apt-mirror
    remote:
      host: apt.releases.hashicorp.com
      root: ''
      scheme: https
      gpg_key: https://apt.releases.hashicorp.com/gpg
    mirror:
      name: hashicorp
      dists:
        - focal
      sections:
        - main
      arches:
        - amd64
    download:
      source: false

  - remote:
      host: packages.microsoft.com
      root: repos/azure-cli
      gpg_key: https://packages.microsoft.com/keys/microsoft.asc
    mirror:
      name: microsoft-azure-cli
      dists:
        - focal
      sections:
        - main
      arches:
        - amd64
    state_cache_days: 0
    download:
      method: http
    output:
      verbose: true

  - remote:
      host: apt.kubernetes.io
      root: ''
      gpg_key: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    mirror:
      name: kubernetes
      dists:
        - kubernetes-xenial
      sections:
        - main
      arches:
        - amd64
    state_cache_days: 0
    download:
      method: http
    output:
      verbose: true

  - remote:
      host: dl.google.com
      root: linux/chrome/deb
      gpg_key: https://dl.google.com/linux/linux_signing_key.pub
    mirror:
      name: google-chrome
      dists:
        - stable
      sections:
        - main
      arches:
        - amd64
    state_cache_days: 0
    download:
      method: http
    output:
      verbose: true

  - remote:
      host: pkg.surfacelinux.com
      root: debian
      gpg_key: https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc
    mirror:
      name: surfacelinux
      dists:
        - release
      sections:
        - main
      arches:
        - amd64
    state_cache_days: 0
    download:
      method: http
    output:
      verbose: true
