grafana:
  adminPassword: prom-operator
  grafana.ini:
    auth:
      oauth_auto_login: true
      disable_signout_menu: false
    auth.generic_oauth:
      enabled: true
      client_id: grafana
      client_secret: $__file{/etc/secrets/auth_generic_oauth/oidc_client_secret}
      scopes: openid email profile
      auth_url: https://k8s-ou.dev.ryezone.com/auth/idp/k8sIdp/auth
      token_url: https://k8s-ou.dev.ryezone.com/auth/idp/k8sIdp/token
      api_url: https://k8s-ou.dev.ryezone.com/auth/idp/k8sIdp/userinfo
      allowed_domains:
      allow_sign_up: true
      tls_skip_verify_insecure: false
      name_attribute_path: name
      # login_attribute_path:
      role_attribute_path: contains(groups[*], 'acl_okta_grafana_admin') && 'Admin' || contains(groups[*], 'acl_okta_grafana_editor') && 'Editor' || 'Viewer'
    log:
      level: debug
    server:
      root_url: https://grafana.dev.ryezone.com
  extraSecretMounts:
    - name: oidc-client-secret
      mountPath: /etc/secrets/auth_generic_oauth
      secretName: grafana-oidc-client-secret
      readOnly: true
