all:
  children:
    external_load_balancer:
      hosts:
        haproxy01:
          ansible_host: haproxy01.dev.ryezone.com
        haproxy02:
          ansible_host: haproxy02.dev.ryezone.com
    kubernetes_cluster:
      children:
        controlplane:
          children:
            initial_controlplane:
              hosts:
                controlplane01:
                  ansible_host: controlplane01.dev.ryezone.com
            additional_controlplane:
              hosts:
                controlplane02:
                  ansible_host: controlplane02.dev.ryezone.com
                controlplane03:
                  ansible_host: controlplane03.dev.ryezone.com
        nodes:
          hosts:
            node01:
              ansible_host: node01.dev.ryezone.com
            node02:
              ansible_host: node02.dev.ryezone.com
            node03:
              ansible_host: node03.dev.ryezone.com
  vars:
    ansible_user: automation-user
    platform_environment: dev
    kubernetes_api_server_vip: 10.5.99.20
    virtual_router_id: 50
    virtual_router_auth_pass: 42