apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cloudflare-api-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acmeCloudflareIssuer.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.cloudflareApiToken | quote }}
