prereq_manifest_files:
  - file: settings/manifests/cloudflare-cluster-issuer.yaml
    targets:
      - aws
      - proxmox

manifest_files:
  - file: /tmp/manifests_csi_nfs_storageclass.yaml
    targets:
      - aws
      - proxmox
  - file: settings/manifests/nfs-server/pvc.yaml
    targets:
      - disable
  - file: settings/manifests/nfs-server/deployment.yaml
    targets:
      - disable
  - file: settings/manifests/nfs-server/service.yaml
    targets:
      - disable
  - file: settings/manifests/nfs-server/storageclass.yaml
    targets:
      - disable
