prereq_manifest_files:
  - file: cloudflare-cluster-issuer.yaml
    targets:
      - aws
      - proxmox

manifest_files:
  - file: nfs-server/pvc.yaml
    targets:
      - proxmox
  - file: nfs-server/deployment.yaml
    targets:
      - proxmox
  - file: nfs-server/service.yaml
    targets:
      - proxmox
  - file: nfs-server/storageclass.yaml
    targets:
      - proxmox
