prereq_manifest_files:
  - name: cloudflare-cluster-issuer
    file: settings/manifests/cloudflare-cluster-issuer.yaml
    targets:
      - aws
      - proxmox
      - dialtone

manifest_files:
  - name: csi-nfs
    file: /tmp/manifests_csi_nfs_storageclass.yaml
    targets:
      - aws
      - proxmox
  - name: nfs-server-pvc
    file: settings/manifests/nfs-server/pvc.yaml
    targets:
      - disable
  - name: nfs-server-deployment
    file: settings/manifests/nfs-server/deployment.yaml
    targets:
      - disable
  - name: nfs-server-service
    file: settings/manifests/nfs-server/service.yaml
    targets:
      - disable
  - name: nfs-server-storageclass
    file: settings/manifests/nfs-server/storageclass.yaml
    targets:
      - disable
