prereq_manifest_files:
  - cloudflare-cluster-issuer.yaml

manifest_files:
  - nfs-server/pvc.yaml
  - nfs-server/deployment.yaml
  - nfs-server/service.yaml
  - nfs-server/storageclass.yaml
  - mssql-server/secrets.yaml
  - mssql-server/pvc.yaml
  - mssql-server/deployment.yaml
  - mssql-server/service.yaml

