secrets:
  - name: cloudflare-api-token-secret
    namespace: cert-manager
    definition:
      data:
        api-token: "{{ cloudflare_api_token | b64encode }}"
      type: Opaque
    targets:
      - aws
      - proxmox
      - dialtone
  - name: admin-pass
    namespace: pihole
    definition:
      data:
        password: "{{ pihole_admin_password | b64encode }}"
      type: Opaque
    targets:
      - aws
      - proxmox
      - dialtone
