templates:
  - src: settings/helm_values/ingress-nginx.yaml.j2
    dest: /tmp/helm_values_ingress-nginx.yaml
    targets:
      - aws
      - proxmox
  - src: settings/helm_values/pihole.yaml.j2
    dest: /tmp/helm_values_pihole.yaml
    targets:
      - aws
      - proxmox
  - src: settings/helm_values/democratic-csi.yaml.j2
    dest: /tmp/helm_values_democratic-csi.yaml
    targets:
      - proxmox
  - src: settings/helm_values/primary-sql-server.yaml.j2
    dest: /tmp/helm_values_primary-sql-server.yaml
    targets:
      - disable
  - src: settings/helm_values/secondary-sql-server.yaml.j2
    dest: /tmp/helm_values_secondary-sql-server.yaml
    targets:
      - disable
  - src: settings/helm_values/bitwarden.yaml.j2
    dest: /tmp/helm_values_bitwarden.yaml
    targets:
      - disable
