templates:
  - src: settings/helm_values/democratic-csi.yaml.j2
    dest: /tmp/helm_values_democratic-csi.yaml
  - src: settings/helm_values/primary-sql-server.yaml.j2
    dest: /tmp/helm_values_primary-sql-server.yaml
  - src: settings/helm_values/secondary-sql-server.yaml.j2
    dest: /tmp/helm_values_secondary-sql-server.yaml
  - src: settings/helm_values/bitwarden.yaml.j2
    dest: /tmp/helm_values_bitwarden.yaml
