templates:
  - name: ingress-nginx
    src: settings/helm_values/ingress-nginx.yaml.j2
    dest: /tmp/helm_values_ingress-nginx.yaml
    targets:
      - aws
      - proxmox
      - dialtone
  - name: pihole
    src: settings/helm_values/pihole.yaml.j2
    dest: /tmp/helm_values_pihole.yaml
    targets:
      - aws
      - proxmox
      - dialtone
  - name: vscode-server
    src: settings/helm_values/vscode-server.yaml.j2
    dest: /tmp/helm_values_vscode-server.yaml
    targets:
      - aws
      - proxmox
      - dialtone
  - name: minecraft
    src: settings/helm_values/minecraft.yaml.j2
    dest: /tmp/helm_values_minecraft.yaml
    targets:
      - aws
      - proxmox
      - dialtone
  - name: democratic-csi
    src: settings/helm_values/democratic-csi.yaml.j2
    dest: /tmp/helm_values_democratic-csi.yaml
    targets:
      - disable
  - name: primary-mssql-server
    src: settings/helm_values/primary-sql-server.yaml.j2
    dest: /tmp/helm_values_primary-sql-server.yaml
    targets:
      - disable
  - name: secondary-mssql-server
    src: settings/helm_values/secondary-sql-server.yaml.j2
    dest: /tmp/helm_values_secondary-sql-server.yaml
    targets:
      - disable
  - name: bitwarden
    src: settings/helm_values/bitwarden.yaml.j2
    dest: /tmp/helm_values_bitwarden.yaml
    targets:
      - disable
  - src: settings/helm_values/postgres-operator.yaml.j2
    dest: /tmp/helm_values_postgres-operator.yaml
    targets:
      - proxmox
  - name: csi-nfs
    src: settings/manifests/csi_nfs_storageclass.yaml.j2
    dest: /tmp/manifests_csi_nfs_storageclass.yaml
    targets:
      - aws
      - proxmox
