cert_manager_helm_chart_version: 1.3.0
cert_manager_helm_chart_repo_name: jetstack
cert_manager_helm_chart_repo_uri: https://charts.jetstack.io
cert_manager_crd_uri: https://github.com/jetstack/cert-manager/releases/download/v{{ cert_manager_helm_chart_version }}/cert-manager.crds.yaml
cert_manager_namespace: cert-manager
cert_manager_enable_prometheus: false
cert_manager_enalbe_service_monitor: false

ansible_k8s_manifests_directory: /opt/ansible/k8s_manifests
ansible_k8s_manifests_owner: automation-user
ansible_k8s_manifests_group: automation-user
kubernetes_pki_directory: /var/lib/rancher/rke2/server/tls
cert_manager_cloudflare_api_token: "{{ lookup ('env', 'CLOUDFLARE_API_TOKEN') }}"
cert_manager_acme_email: no-reply@example.com
acme_server: https://acme-v02.api.letsencrypt.org/directory
