---
platform_environment: dev
cloudflare:
  api_token: "{{ lookup ('env', 'CLOUDFLARE_API_TOKEN') }}"
  zone: ryezone.com


kubernetes_api_server_vip: 10.5.99.20
kubernetes_api_server_port: 6443
kubernetes_zone: "{{ platform_environment }}.{{ cloudflare.zone }}"
kubernetes_advertise_address: "{{ ansible_all_ipv4_addresses[0] }}"
kubernetes_control_plane_endpoint_vip: "{{ kubernetes_api_server_vip }}"
kubernetes_control_plane_endpoint_port: "{{ kubernetes_api_server_port }}"

kubernetes_cni_calicoctl_version: v3.18.0
kubernetes_cni_calicoctl_checksum: sha256:7152bdda15c9fd2c4723004931def11989e20fa0884f4fc45ae8b61cc836cd19
kubernetes_package_signing_key_id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
kubernetes_kubeadm_release: xenial

helm_chart_version_cert_manager: 1.2.0
helm_chart_version_ingress_nginx: 3.23.0
helm_chart_version_linkerd: 2.9.4
helm_chart_version_prometheus: 13.13.1

cert_manager_cloudflare_account_email: "{{ lookup('env', 'CLOUDFLARE_ACCOUNT_EMAIL') }}"
cert_manager_cloudflare_api_key: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"