keepalived_virtual_router_id: 50
keepalived_auth_pass: 42
keepalived_vip: "{{ kubernetes_api_server_vip }}"
keepalived_interface: eth0
keepalived_check_port: "{{ kubernetes_api_server_port }}"
haproxy_frontends:
  - name: apiserver
    bind_address: "*"
    bind_port: "{{ kubernetes_api_server_port }}"
    mode: tcp
    default_backend: apiserver
    options:
      - tcplog
  - name: http-ingress
    bind_address: "*"
    bind_port: 80
    mode: tcp
    default_backend: http-ingress
    options:
      - tcplog
  - name: https-ingress
    bind_address: "*"
    bind_port: 443
    mode: tcp
    default_backend: https-ingress
    options:
      - tcplog
haproxy_backends:
  - name: apiserver
    mode: tcp
    balance_method: roundrobin
    options:
      - httpchk GET /healthz
      - ssl-hello-chk
    http_checks:
      - expect status 200
    servers:
      - name: controlplane01
        address: "controlplane01.{{ kubernetes_zone }}"
        port: 6443
      - name: controlplane02
        address: "controlplane02.{{ kubernetes_zone }}"
        port: 6443
      - name: controlplane03
        address: "controlplane03.{{ kubernetes_zone }}"
        port: 6443
  - name: http-ingress
    mode: tcp
    balance_method: roundrobin
    options:
      - httpchk GET /healthz
    http_checks:
      - expect status 200
    servers:
      - name: node01
        address: "node01.{{ kubernetes_zone }}"
        port: 80
      - name: node02
        address: "node02.{{ kubernetes_zone }}"
        port: 80
      - name: node03
        address: "node03.{{ kubernetes_zone }}"
        port: 80
  - name: https-ingress
    mode: tcp
    balance_method: roundrobin
    options:
      - httpchk GET /healthz
      - ssl-hello-chk
    http_checks:
      - expect status 200
    servers:
      - name: node01
        address: "node01.{{ kubernetes_zone }}"
        port: 443
      - name: node02
        address: "node02.{{ kubernetes_zone }}"
        port: 443
      - name: node03
        address: "node03.{{ kubernetes_zone }}"
        port: 443
