all:
  hosts:
    localhost:
  vars:
    apt_repos:
      - name: linux-surface
        repo: https://apt.ryezone.com/surfacelinux/ release main
        arch: amd64
        key_url: https://apt.ryezone.com/surfacelinux/gpg
      - name: yubico
        repo: https://apt.ryezone.com/yubico-stable/ focal main
        arch: amd64
        key_url: https://apt.ryezone.com/yubico-stable/gpg
      - name: docker
        repo: https://apt.ryezone.com/docker/ focal stable
        arch: amd64
        key_url: https://apt.ryezone.com/docker/gpg
    firewall_ipv6_enabled: true
    firewall_rules_allow_inbound_v4: []
    firewall_rules_allow_outbound_v4: []
    firewall_rules_allow_inbound_v6: []
    firewall_rules_allow_outbound_v6: []
    golang_version: '1.17.2'
    primary_user: ubuntu
