---
- name: download rke2 installer
  ansible.builtin.get_url:
    url: https://get.rke2.io
    dest: /tmp/install.sh
    mode: 750

- name: create manifest dir
  ansible.builtin.file:
    path: /var/lib/rancher/rke2/server/manifests/
    state: directory

- name: deploy rke2-ingress-nginx manifest
  ansible.builtin.template:
    src: rke2-ingress-nginx.yaml.j2
    dest: /var/lib/rancher/rke2/server/manifests/rke2-ingress-nginx-config.yaml

- name: run rke2 installer
  ansible.builtin.command:
    argv:
      - /tmp/install.sh
  environment:
    INSTALL_RKE2_CHANNEL: "{{install_rke2_channel}}"
    INSTALL_RKE2_TYPE: "{{install_rke2_type}}"
    INSTALL_RKE2_VERSION: "{{install_rke2_version}}"
  args:
    creates: /usr/local/bin/rke2

- name: copy systemd service to /etc/systemd
  ansible.builtin.copy:
    remote_src: yes
    src: /usr/local/lib/systemd/system/rke2-{{ node_type }}.service
    dest: /etc/systemd/system/rke2-{{ node_type }}.service
  # notify: reload systemd

- name: create rke2 config dir
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory

- name: deploy rke2 config
  ansible.builtin.template:
    src: rke2_config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml

- name: enable rke2-{{ node_type }}
  ansible.builtin.systemd:
    name: rke2-{{ node_type }}
    state: started
    enabled: yes
    daemon-reload: yes

- name: restart rke2-{{ node_type }}
  ansible.builtin.systemd:
    name: rke2-{{ node_type }}
    state: restarted
  when: not is_initial_node


- name: pause for {{ node_ready_timeout }} minutes for node to initialize.
  ansible.builtin.pause:
    minutes: "{{ node_ready_timeout }}"
  when: not is_agent_node


- name: add a link to kubectl binary
  ansible.builtin.file:
    state: link
    path: /usr/local/bin/kubectl
    src: /var/lib/rancher/rke2/bin/kubectl
  when: not is_agent_node

- name: create .kube directory
  ansible.builtin.file:
    state: directory
    path: /home/automation-user/.kube
    owner: automation-user
    group: automation-user
  when: not is_agent_node

- name: copy kubeconfig to ansible user directory
  ansible.builtin.copy:
    dest: /home/automation-user/.kube/config
    remote_src: true
    src: /etc/rancher/rke2/rke2.yaml
    owner: automation-user
    group: automation-user
    mode: 0600
  when: not is_agent_node