- name: install base cluster configuration
  import_playbook: base_cluster_config.yml

- hosts: node
  roles:
    - nitrokey_hsm
  tags:
    - hsm

- hosts: localhost
  connection: local
  roles:
    - sonatype_nexus
    - configure_sonatype_nexus