- hosts: all_cluster_vms
  connection: local
  tasks:
  - name: compute dns values
    ansible.builtin.set_fact:
     values_from_inv:
       cloudflare_value: "{{ proxmox_ipconfig0.ip | ipaddr('address') }}"
       cloudflare_record: "{{ proxmox_name | replace('.'+cloudflare_zone, '') }}"

  - name: output computed dns values
    ansible.builtin.debug:
       var: values_from_inv

  - name: Set DNS A Records
    community.general.cloudflare_dns:
      zone: "{{ cloudflare_zone }}"
      api_token: "{{ cloudflare_api_token }}"
      type: A
      value: "{{ values_from_inv.cloudflare_value }}"
      record: "{{ values_from_inv.cloudflare_record }}"
      state: present

- hosts: initial_controlplane
  connection: local
  tasks:
  - name: Set DNS A Records
    community.general.cloudflare_dns:
      zone: "{{ cloudflare_zone }}"
      api_token: "{{ cloudflare_api_token }}"
      type: A
      value: "{{ vip.cloudflare_value }}"
      record: "{{ vip.cloudflare_record }}"
      state: present
    loop_control:
      loop_var: vip
    loop: "{{ cluster_vips }}"

- hosts: all_cluster_vms
  roles:
    - firewall

- hosts: external_load_balancer
  roles:
    - rke2_load_balancer

- hosts: initial_controlplane
  roles:
    - rke2

- hosts: additional_controlplane
  roles:
    - rke2
  serial: 1

- hosts: node
  roles:
    - rke2

- name: install base cluster configuration
  import_playbook: base_cluster_config.yml
