ubuntu-autoinstall-iso:
  hosts:
    localhost:
  vars:
    iso_url: https://releases.ubuntu.com/20.04.4/ubuntu-20.04.4-live-server-amd64.iso
    iso_checksum: sha256:28ccdb56450e643bad03bb7bcf7507ce3d8d90e8bf09e38f6bd9ac298a98eaad
    iso_name: ubuntu-20.04.4-live-server-amd64.iso

packer_ubuntu_proxmox:
  hosts:
    packer_ubuntu_2004_proxmox:

packer_ubuntu_virtualbox:
  hosts:
    packer_ubuntu_2004_virtualbox:

packer_ubuntu_vmware:
  hosts:
    packer_ubuntu_2004_vmware:

proxmox_hosts:
  hosts:
    proxmox01.ryezone.com:
    proxmox02.ryezone.com:

packer_ubuntu:
  children:
    packer_ubuntu_proxmox:
    packer_ubuntu_virtualbox:
    packer_ubuntu_vmware:

bare_metal_ubuntu:
  hosts:
    maas01:
    plex.rye.ninja:

ubuntu:
  children:
    packer_ubuntu:
    bare_metal_ubuntu:

packer_proxmox:
  children:
    packer_ubuntu_proxmox:

all:
  children:
    ubuntu-autoinstall-iso:
    ubuntu:
