is_initial_node: false
is_agent_node: true

firewall_rules_allow_inbound_v4:
  - name: HTTP
    protocol: tcp
    port: 80
  - name: HTTPS
    protocol: tcp
    port: 443
  - name: RancherD/RKE2 Flannel VXLAN
    protocol: udp
    port: 8472
  - name: Rancher Monitoring Node Exporter
    protocol: tcp
    port: 9796
  - name: Kubernetes Kubelet API
    protocol: tcp
    port: 10250

firewall_rules_allow_outbound_v4: []

firewall_ipv6_enabled: false
firewall_rules_allow_inbound_v6: []
firewall_rules_allow_outbound_v6: []

nitrokey_hsm_init_status_override: false
