haproxy_frontends:
  - name: api-server
    bind_address: "*"
    bind_port: 6443
    mode: tcp
    default_backend: api-server
    options:
      - tcplog
  - name: node-join
    bind_address: "*"
    bind_port: 9345
    mode: tcp
    default_backend: node-join
    options:
      - tcplog
  - name: http-ingress
    bind_address: "*"
    bind_port: 80
    mode: tcp
    default_backend: http-ingress
    options:
      - tcplog
  - name: https-ingress
    bind_address: "*"
    bind_port: 443
    mode: tcp
    default_backend: https-ingress
    options:
      - tcplog

haproxy_backends:
  - name: api-server
    mode: tcp
    port: 6443
    balance_method: roundrobin
    options:
      - httpchk GET /healthz
      - ssl-hello-chk
    http_checks:
      - expect status 200
    servers: "{{ rke2_controlplane_servers }}"
  - name: node-join
    mode: tcp
    port: 9345
    check_options: check-ssl verify none
    balance_method: roundrobin
    options:
      - httpchk GET /ping
    http_checks:
      - expect status 200
    servers: "{{ rke2_controlplane_servers }}"
  - name: http-ingress
    mode: tcp
    port: 80
    balance_method: roundrobin
    options:
      - httpchk GET /healthz
    http_checks:
      - expect status 200
    servers: "{{ rke2_controlplane_servers }}"
  - name: https-ingress
    mode: tcp
    port: 443
    balance_method: roundrobin
    options:
      - httpchk GET /healthz
      - ssl-hello-chk
    http_checks:
      - expect status 200
    servers: "{{ rke2_controlplane_servers }}"
