- name: IPV4 - Allow Inbound rke2 Controlplane traffic from Everyone
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    jump: ACCEPT
    destination_port: "{{ inbound_service_ipv4_controlplane.port }}"
    protocol: "{{ inbound_service_ipv4_controlplane.protocol }}"
    comment: "{{ inbound_service_ipv4_controlplane.service }}"
    ctstate:
      - NEW
    wait: "{{ firewall_wait_lock_seconds }}"
  become: true
  loop_control:
    loop_var: inbound_service_ipv4_controlplane
  loop:
    - service: etcd client api
      protocol: tcp
      port: 2379
    - service: etcd peer api
      protocol: tcp
      port: 2380
    - service: Kubernetes API Server
      protocol: tcp
      port: 6443
    - service: RancherD/RKE2 Flannel VXLAN
      protocol: udp
      port: 8472
    - service: RKE2 Node Join
      protocol: tcp
      port: 9345
    - service: Kubernetes Kubelet API
      protocol: tcp
      port: 10250
    - service: Kubernetes Kube Scheduler
      protocol: tcp
      port: 10251
    - service: Kubernetes Kube Controller Manager
      protocol: tcp
      port: 10252
  notify:
    - persist iptables
  when:
    - firewall_role == 'rke2_controlplane'
