- name: IPV4 - Allow Inbound rke2 Node traffic from Everyone
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    jump: ACCEPT
    destination_port: "{{ inbound_service_ipv4_haproxy.port }}"
    protocol: "{{ inbound_service_ipv4_haproxy.protocol }}"
    comment: "{{ inbound_service_ipv4_haproxy.service }}"
    ctstate:
      - NEW
    wait: "{{ firewall_wait_lock_seconds }}"
  become: true
  loop_control:
    loop_var: inbound_service_ipv4_haproxy
  loop:
    - service: HTTP
      protocol: tcp
      port: 80
    - service: HTTPS
      protocol: tcp
      port: 443
    - service: Kubernetes API
      protocol: tcp
      port: 6443
    - service: HAProxy Stats Page
      protocol: tcp
      port: 8000
    - service: RKE2 Node Join
      protocol: tcp
      port: 9345
