- name: Set Inbound Services by Role - rke2_controlplane_rancher
  ansible.builtin.set_fact:
    firewall_allow_inbound_services_exposed_to_everyone:
      - service: HTTP
        protocol: tcp
        port: 80
      - service: HTTPS
        protocol: tcp
        port: 443
      - service: etcd client api
        protocol: tcp
        port: 2379
      - service: etcd peer api
        protocol: tcp
        port: 2380
      - service: Kubernetes API Server
        protocol: tcp
        port: 6443
      - service: RancherD/RKE2 Flannel VXLAN
        protocol: udp
        port: 8472
      - service: RKE2 Node Join
        protocol: tcp
        port: 9345
      - service: Kubernetes Kubelet API
        protocol: tcp
        port: 10250
      - service: Kubernetes Kube Scheduler
        protocol: tcp
        port: 10251
      - service: Kubernetes Kube Controller Manager
        protocol: tcp
        port: 10252
