---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - group_vars/all.yml
  tasks:
  - name: Set A Records
    community.general.cloudflare_dns:
      zone: "{{ cloudflare.zone }}"
      api_token: "{{ cloudflare.api_token }}"
      type: A
      value: "{{ item.value }}"
      record: "{{ item.record }}.{{ platform_environment }}"
      state: present
    loop: "{{ dns_entries }}"

  - name: pause for 1 minutes for dns to propagate.
    ansible.builtin.pause:
      minutes: 1
