- hosts: all
  tasks:
    - name: flush all rules
      ansible.builtin.command: iptables -F
  become: true

- hosts: all
  roles:
    - firewall
  become: true

- hosts: initial_controlplane
  tasks:
    - name: list kube-proxy pods
      community.kubernetes.k8s_info:
        api_version: v1
        kind: Pod
        namespace: kube-system
        label_selectors:
          - k8s-app = kube-proxy
      register: kube_proxy_pod_list
    
    - name: delete kube-proxy pods
      community.kubernetes.k8s:
        state: absent
        api_version: "{{ item.apiVersion }}"
        kind: "{{ item.kind }}"
        name: "{{ item.metadata.name }}"
        namespace: "{{ item.metadata.namespace }}"
      loop: "{{ kube_proxy_pod_list.resources }}"