- name: Apply DNS
  import_playbook: rancher_00_dns.yml

- name: Apply Host Entries
  import_playbook: rancher_01_host_files.yml

- name: Provision Load Balancers
  import_playbook: rancher_02_haproxy.yml

- name: Provision RKE2 server nodes
  import_playbook: rancher_03_rke2.yml

# - name: Install apps.
#   include: rancher_06_install_apps.yml
