apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mssql-operator-ag1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mssql-operator-ag1
subjects:
- kind: ServiceAccount
  name: mssql-operator
  namespace: ag1
