apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mssql-server.fullname" . }}
  labels:
    {{- include "mssql-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      {{- include "mssql-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mssql-server.selectorLabels" . | nindent 8 }}
    spec:
      hostname: {{ include "mssql-server.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - /bin/bash
            - -c
            - cp /var/opt/config/mssql.conf /var/opt/mssql/mssql.conf && /opt/mssql/bin/sqlservr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mssql
              containerPort: 1433
              protocol: TCP
          env:
            - name: MSSQL_PID
              value: "{{ .Values.MSSQL_PID.value}}"
            - name: ACCEPT_EULA
              value: "{{ .Values.ACCEPT_EULA.value | upper}}"
            - name: MSSQL_AGENT_ENABLED
              value: "{{ .Values.MSSQL_AGENT_ENABLED.value}}"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mssql-server.secretName" . }}
                  key: sa_password
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql
            - name: mssqluserdb
              mountPath: /var/opt/mssql/userdata
            - name: mssqllog
              mountPath: /var/opt/mssql/userlog
            - name: mssqltemp
              mountPath: /var/opt/mssql/tempdb
            - name: mssql-config-volume
              mountPath: /var/opt/config
            {{- if .Values.logShipping.enabled }}
            - name: log-shipping-volume
              mountPath: /var/opt/mssql/logship
            {{- end }}
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: {{ include "mssql-server.mssqlsqldataPVCName" . }}
        - name: mssqluserdb
          persistentVolumeClaim:
            claimName: {{ include "mssql-server.mssqluserdbPVCName" . }}
        - name: mssqllog
          persistentVolumeClaim:
            claimName: {{ include "mssql-server.mssqllogPVCName" . }}
        - name: mssqltemp
          persistentVolumeClaim:
            claimName: {{ include "mssql-server.mssqltempPVCName" . }}
        {{- if .Values.logShipping.enabled }}
        - name: log-shipping-volume
          persistentVolumeClaim:
            claimName: {{ include "mssql-server.logShippingClaimName" . }}
        {{- end }}
        - name: mssql-config-volume
          configMap:
            name: {{ include "mssql-server.configMapName" . }}
