apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql-server.fullname" . }}
  labels:
    {{- include "mssql-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mssql
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "mssql-server.selectorLabels" . | nindent 4 }}
{{- if and (eq "LoadBalancer" .Values.service.type) (not (eq "" (.Values.service.loadBalancerIP | default "" ))) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end -}}
{{- if and (eq "ClusterIP" .Values.service.type) (not (eq "" (.Values.service.clusterIP | default "" ))) }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end -}}
