---
- name: set facts
  ansible.builtin.include_vars:
    file: "{{ haproxy_role }}.yml"
  when:
    - haproxy_role != 'default'

- name: Ensure HAProxy is installed.
  package:
    name: haproxy
    state: present
  become: true

- name: Ensure HAProxy is enabled (so init script will start it on Debian).
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$"
    line: "ENABLED=1"
    state: present
  when: ansible_os_family == 'Debian'
  become: true

- name: Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy
  become: true

- name: Ensure HAProxy is started and enabled on boot.
  service:
    name: haproxy
    state: started
    enabled: yes
  become: true
