- name: create directory for encrypted keys
  ansible.builtin.file:
    path: /etc/hsm
    mode: 0750
    state: directory
    owner: root
    group: root
  become: true

- name: copy extracted bank-vaults key to node
  ansible.builtin.copy:
    src: /tmp/pki/
    dest: /etc/hsm

- name: find all keys to import
  ansible.builtin.find:
    depth: 1
    file_type: file
    paths:
      - /etc/hsm
    patterns:
      - '*.wrap-key.bin'
  register: keys_to_import

- name: debug keys_to_import
  ansible.builtin.debug:
    var: keys_to_import

- name: loop through imported keys
  ansible.builtin.include_tasks:
    file: import_key.yml
  loop_control:
    loop_var: imported_key
  loop: "{{ keys_to_import.files }}"
