- name: create directory for encrypted keys
  ansible.builtin.file:
    path: /etc/hsm
    mode: 0750
    state: directory
    owner: root
    group: root
  become: true

# TODO:
#  - I need to figure out how nodes 02 and 03 will get hsm_bank_vaults_key_ref_id
#  - initial thoughts are having node 01 write a json list to a file [ { id: name } ]
#  - and copy it to the container.

- name: copy extracted bank-vaults key to node
  ansible.builtin.copy:
    src: /tmp/pki/{{ hsm_bank_vaults_key_ref_id }}.bank-vaults.wrap-key.bin
    dest: /etc/hsm/{{ hsm_bank_vaults_key_ref_id }}.bank-vaults.wrap-key.bin
