apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=./Dockerfile"
    - "--context=tar://stdin"
    - "--destination=docker.io/estenrye/ansible:test"
    volumeMounts:
      - name: docker-secret
        mountPath: /kaniko/.docker/config.json
    resources:
      limits:
        cpu: 2.0
        memory: 1024m
  restartPolicy: Never
  volumes:
    - name: docker-secret
      secret:
        secretName: docker-secret
