---
haproxy_user: haproxy
haproxy_group: haproxy
haproxy_role: default
haproxy_global_vars: []
haproxy_frontends: []
haproxy_backends: []

# TODO: Leverage the inventory more for defining this.
# Needs to be overridable.  Example: rancher cluster has only controlplane nodes
rke2_controlplane_servers:
  - name: controlplane01
    address: controlplane01.{{ kubernetes_zone }}
  - name: controlplane02
    address: controlplane02.{{ kubernetes_zone }}
  - name: controlplane03
    address: controlplane03.{{ kubernetes_zone }}

# TODO: Leverage the inventory more for defining this.
# Needs to be overridable.  Example: rancher cluster has only controlplane nodes
rke2_ingress_servers:
  - name: node01
    address: node01.{{ kubernetes_zone }}
  - name: node02
    address: node02.{{ kubernetes_zone }}
  - name: node03
    address: node03.{{ kubernetes_zone }}

