---
# handlers file for edge_firewall
- name: save iptables v4 rules
  shell: >-
    iptables-save |
    sed '/^-A KUBE/d' |
    sed '/^-A cali/d' |
    sed '/^-A PREROUTING/d' |
    sed '/^-A POSTROUTING/d' |
    sed '/^:KUBE/d' |
    sed '/^:cali/d' |
    sed '/cali-INPUT$/d' |
    sed '/cali-FORWARD$/d' |
    sed '/cali-OUTPUT$/d' |
    sed '/KUBE-FORWARD$/d' |
    sed '/KUBE-FIREWALL$/d'
    > /etc/iptables/rules.v4
  listen: persist iptables
  become: yes

- name: save iptables v6 rules
  shell: >-
    ip6tables-save |
    sed '/^-A KUBE/d' |
    sed '/^-A cali/d' |
    sed '/^-A PREROUTING/d' |
    sed '/^-A POSTROUTING/d' |
    sed '/^:KUBE/d' |
    sed '/^:cali/d' |
    sed '/cali-INPUT$/d' |
    sed '/cali-FORWARD$/d' |
    sed '/cali-OUTPUT$/d' |
    sed '/KUBE-FORWARD$/d' |
    sed '/KUBE-FIREWALL$/d'
    > /etc/iptables/rules.v6
  listen: persist iptables
  become: yes
