---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker

platforms:
  - name: instance
    image: docker.io/estenrye/ansible
    pre_build_image: true
    networks:
      - name: molecule-k3s
    volumes:
      - /tmp/.kube:/home/automation-user/.kube:rw
  - name: controlplane
    image: docker.io/rancher/k3s:v1.21.6-k3s1
    pre_build_image: true
    command:
      - server
      - --cluster-cidr=10.50.0.0/16
      - --service-cidr=10.51.0.0/16
      - --cluster-dns=10.51.0.10
      - --write-kubeconfig=/.kube/config
      - --write-kubeconfig-mode=666
      - --node-taint=CriticalAddonsOnly=true:NoExecute
      - --token=blah-blah-blah
    volumes:
      - /tmp/.kube:/.kube:rw
    privileged: true
    exposed_ports:
      - 6443/tcp
      - 80/tcp
      - 443/tcp
    networks:
      - name: molecule-k3s
    groups:
      - controlplane
  - name: node
    image: docker.io/rancher/k3s:v1.21.6-k3s1
    pre_build_image: true
    command:
      - agent
      - --server=https://controlplane:6443
      - --token=blah-blah-blah
    privileged: true
    exposed_ports:
      - 80/tcp
      - 443/tcp
    networks:
      - name: molecule-k3s
    groups:
      - nodes

provisioner:
  name: ansible
  playbooks:
    prepare: ../../../../molecule/prepare.yml
    cleanup: ../../../../molecule/cleanup.yml
    converge: converge.yml
    verify: verify.yml
  inventory:
    group_vars:
      all:
        kube_config: /home/automation-user/.kube/config
verifier:
  name: ansible
