apt_mirror: http://apt.ryezone.com/ubuntu

user:
  realname: Automation User
  username: automation-user
  password_plaintext: "{{ lookup('password', '/output/{{ inventory_hostname }}/password length=16 chars=ascii_letters,digits') }}"
  password_salt: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"

user_data_template: /ansible/templates/user-data_bios.yml.j2
# user_data_template: /ansible/templates/user-data_uefi.yml.j2

keyboard:
  layout: us

locale: en_US.utf8

disks:
  additional_disks: []
  boot:
    device_path: /dev/sda
    size: 100G
    additional_partitions:
      - id: 3
        name: root
        mount_path: /
        size: 40G
      - id: 4
        name: var
        mount_path: /var
        size: 2G
      - id: 5
        name: var-log
        mount_path: /var/log
        size: 15G
      - id: 6
        name: var-log-audit
        mount_path: /var/log/audit
        size: 4G
      - id: 7
        name: var-tmp
        mount_path: /var/tmp
        mount_options: nodev,nosuid,noexec
        size: 7G
      - id: 8
        name: home
        mount_path: /home
        mount_options: nodev
        size: 2G
      - id: 9
        name: var-lib
        mount_path: /var/lib
        size: -1
