- name: Create Configuration Directories
  ansible.builtin.file:
    path: "{{ item }}"
    group: root
    owner: root
    state: directory
  loop:
    - /etc/keepalived
  become: true

- name: Create Configuration Files
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: "644"
    owner: root
    group: root
  notify: restart keepalived
  become: true

- name: Install Packages
  ansible.builtin.package:
    name: keepalived
  become: true

- name: Ensure keepalived is enabled on boot.
  ansible.builtin.service:
    name: keepalived
    enabled: yes
  become: true

- name: Ensure keepalived is started.
  ansible.builtin.service:
    name: keepalived
    state: started
  become: true
