firewall_bogus_block_loopback_subnet: true
firewall_wait_lock_seconds: "5"
firewall_allow_outbound_requests_to_everyone: []
  # - service: Kubernetes API
  #   protocol: tcp
  #   port: 6443
  # - service: HAProxy Stats Page
  #   protocol: tcp
  #   port: 8000
  # - service: RKE2 Node Join
  #   protocol: tcp
  #   port: 9345

firewall_allow_inbound_services_exposed_to_everyone: []
  # - service: Kubernetes API
  #   protocol: tcp
  #   port: 6443
  # - service: HAProxy Stats Page
  #   protocol: tcp
  #   port: 8000
  # - service: RKE2 Node Join
  #   protocol: tcp
  #   port: 9345

ipv6_enabled: false
firewall_role: default
