- hosts: 127.0.0.1
  connection: local
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: Add Kubernetes Package Signing Key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /etc/apt/trusted.gpg.d/google_cloud_packages.gpg
        id: "{{ kubernetes_package_signing_key_id }}"
        state: present
      become: true

    - name: Add Package Repositories
      ansible.builtin.apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-{{ kubernetes_kubeadm_release }} main"
        filename: /etc/apt/sources.list.d/kubernetes
        state: present
      become: true
    
    - name: Install Kubernetes Packages
      ansible.builtin.apt:
        name: kubectl
      become: true

    - name: Install calicoctl
      ansible.builtin.get_url:
        url: https://github.com/projectcalico/calicoctl/releases/download/{{ kubernetes_cni_calicoctl_version }}/calicoctl
        checksum: "{{ kubernetes_cni_calicoctl_checksum }}"
        dest: /usr/local/bin/kubectl-calico
        mode: 0755
        owner: root
        group: root
      become: true