---
- hosts: external_load_balancer
  roles:
    - haproxy
    - keepalived
  vars:
    # TODO: Refactor haproxy_frontends to use a map rather than a list, will make it easier to override.
    haproxy_frontends:
      - name: apiserver
        bind_address: "*"
        bind_port: "{{ kubernetes_api_server_port }}"
        mode: tcp
        default_backend: apiserver
        options:
          - tcplog
      - name: http-ingress
        bind_address: "*"
        bind_port: 80
        mode: tcp
        default_backend: http-ingress
        options:
          - tcplog
      - name: https-ingress
        bind_address: "*"
        bind_port: 443
        mode: tcp
        default_backend: https-ingress
        options:
          - tcplog
    # TODO: Refactor haproxy_backends to use a map rather than a list, will make it easier to override.
    haproxy_backends:
      - name: apiserver
        mode: tcp
        balance_method: roundrobin
        options:
          - httpchk GET /healthz
          - ssl-hello-chk
        http_checks:
          - expect status 200
        servers:
          - name: controlplane01
            address: "controlplane01.{{ kubernetes_zone }}"
            port: 6443
          - name: controlplane02
            address: "controlplane02.{{ kubernetes_zone }}"
            port: 6443
          - name: controlplane03
            address: "controlplane03.{{ kubernetes_zone }}"
            port: 6443
      - name: http-ingress
        mode: tcp
        balance_method: roundrobin
        options:
          - httpchk GET /healthz
        http_checks:
          - expect status 200
        servers:
          - name: node01
            address: "node01.{{ kubernetes_zone }}"
            port: 32080
          - name: node02
            address: "node02.{{ kubernetes_zone }}"
            port: 32080
          - name: node03
            address: "node03.{{ kubernetes_zone }}"
            port: 32080
      - name: https-ingress
        mode: tcp
        balance_method: roundrobin
        options:
          - httpchk GET /healthz
          - ssl-hello-chk
        http_checks:
          - expect status 200
        servers:
          - name: node01
            address: "node01.{{ kubernetes_zone }}"
            port: 32443
          - name: node02
            address: "node02.{{ kubernetes_zone }}"
            port: 32443
          - name: node03
            address: "node03.{{ kubernetes_zone }}"
            port: 32443

- hosts: kubernetes_cluster
  roles:
    - kubernetes

- hosts:
    - initial_controlplane
  roles:
    - kubernetes_cluster_node

- hosts:
    - additional_controlplane
  serial: 1
  roles:
    - kubernetes_cluster_node

- hosts:
    - nodes
  roles:
    - kubernetes_cluster_node
