kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
  disableDefaultCNI: true
  apiServerPort: 6443
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: "10.96.0.1/12"
    podSubnet: "10.240.0.0/16"
nodes:
  - role: control-plane
  - role: control-plane
  - role: control-plane
  - role: worker
    extraPortMappings:
    - containerPort: 32080
      hostPort: 10080
    - containerPort: 32443
      hostPort: 10443
  - role: worker
    extraPortMappings:
    - containerPort: 32080
      hostPort: 20080
    - containerPort: 32443
      hostPort: 20443
  - role: worker
    extraPortMappings:
    - containerPort: 32080
      hostPort: 30080
    - containerPort: 32443
      hostPort: 30443
