apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-kube-prome-alertmanager
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClassName }}
    cert-manager.io/issuer: {{ .Values.certManagerIssuer }}

spec:
  tls:
  - hosts:
    - alertmanager.{{ .Values.zone }}
    secretName: {{ .Release.Name }}-kube-prome-alertmanager-tls
  rules:
  - host: alertmanager.{{ .Values.zone }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.kubePrometheusStackReleaseName }}-kube-prome-alertmanager
            port:
              number: 9093