---
- name: Allow icmp echo-request from Friends
  ansible.builtin.iptables:
    table: filter
    chain: Allow
    jump: Friends
    protocol: icmp
    icmp_type: echo-request
    wait: "{{ firewall_wait_lock_seconds }}"
  become: true
  notify:
    - persist iptables

- name: Allow icmp echo-request from Friends
  ansible.builtin.iptables:
    table: filter
    chain: Allow
    jump: ACCEPT
    protocol: icmp
    icmp_type: any
    limit: 1/second
    wait: "{{ firewall_wait_lock_seconds }}"
  become: true
  notify:
    - persist iptables

- name: Drop icmp requests
  ansible.builtin.iptables:
    table: filter
    chain: Allow
    jump: DROP
    protocol: icmp
    icmp_type: any
    wait: "{{ firewall_wait_lock_seconds }}"
  become: true
  notify:
    - persist iptables

- name: Accept Packets for services exposed externally to Friends
  ansible.builtin.iptables:
    table: filter
    chain: Allow
    jump: Friends
    destination_port: "{{ item.port }}"
    protocol: "{{ item.protocol }}"
    comment: "{{ item.service }}"
    wait: "{{ firewall_wait_lock_seconds }}"
  become: true
  loop: "{{ firewall_allow_inbound_services_exposed_to_friends }}"
  notify:
    - persist iptables

- name: Accept Packets for services exposed externally to Everyone
  ansible.builtin.iptables:
    table: filter
    chain: Allow
    jump: ACCEPT
    destination_port: "{{ item.port }}"
    protocol: "{{ item.protocol }}"
    comment: "{{ item.service }}"
    wait: "{{ firewall_wait_lock_seconds }}"
  become: true
  loop: "{{ firewall_allow_inbound_services_exposed_to_everyone }}"
  notify:
    - persist iptables

- name: Deny Packets for services not explicitly allowed.
  ansible.builtin.iptables:
    table: filter
    chain: Allow
    jump: DROP
    wait: "{{ firewall_wait_lock_seconds }}"
  become: true
  notify:
    - persist iptables
