---
- name: Accept packets from known hosts.
  ansible.builtin.iptables:
    table: filter
    chain: Friends
    jump: ACCEPT
    source: "{{ item }}"
    wait: "{{ firewall_wait_lock_seconds }}"
  become: true
  loop: "{{ firewall_friends_known_cidr }}"
  notify:
    - persist iptables

- name: Block packets from unknown hosts
  ansible.builtin.iptables:
    table: filter
    chain: Friends
    jump: DROP
    wait: "{{ firewall_wait_lock_seconds }}"
  become: true
  notify:
    - persist iptables
