- name: set facts
  ansible.builtin.include_vars:
    file: "{{ firewall_role }}.yml"
  when:
    - firewall_role != 'default'

- ansible.builtin.include_tasks:
    file: "{{ item }}"
  loop:
    - main/cis_ubuntu_2004_3.5.3.1.1.yml
    - main/cis_ubuntu_2004_3.5.3.1.2.yml
    - main/cis_ubuntu_2004_3.5.3.1.3.yml
    - main/cis_ubuntu_2004_3.5.3.2.2.yml
    - main/cis_ubuntu_2004_3.5.3.2.3.yml
    - main/cis_ubuntu_2004_3.5.3.2.4.yml
    - main/cis_ubuntu_2004_3.5.3.2.1.yml
    - main/cis_ubuntu_2004_3.5.3.3.2.yml
    - main/cis_ubuntu_2004_3.5.3.3.3.yml
    - main/cis_ubuntu_2004_3.5.3.3.4.yml
    - main/cis_ubuntu_2004_3.5.3.3.1.yml
