# tasks file for edge_firewall
- name: Create iptables configuration directory.
  file:
    path: /etc/iptables
    state: directory
  become: true

- name: Get existing iptables rules
  command: iptables -n -L
  changed_when: false
  register: iptables_rules
  become: true

- name: Create custom iptables chain
  command: iptables -N '{{ item }}'
  when: "'Chain {{ item }}' not in iptables_rules.stdout"
  become: true
  loop:
    - Always
    - Allow
    - Bogus
    - Enemies
    - Friends
  notify:
    - persist iptables

- name: INPUT chain
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    jump: "{{ item }}"
  become: true
  loop:
    - Bogus
    - Always
    - Enemies
    - Allow
  notify:
    - persist iptables

- name: FORWARD chain
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    jump: "{{ item }}"
  become: true
  loop:
    - Bogus
    - Always
    - Enemies
    - Allow
  notify:
    - persist iptables

- name: Add Bogus Packet Rules
  include_tasks: bogus_packets.yml

- name: Add Always Packet Rules
  include_tasks: always.yml

- name: Add Friends Packet Rules
  include_tasks: friends.yml

- name: Add Enemies Packet Rules
  include_tasks: enemies.yml

- name: Add Allow Packet Rules
  include_tasks: allow.yml