- name: Install iptables
  ansible.builtin.package:
    name: iptables
  become: true  

- name: Install iptables-persistent
  ansible.builtin.package:
    name: iptables-persistent
  become: true

- name: Create iptables configuration directory.
  file:
    path: /etc/iptables
    state: directory
  become: true

- name: Create custom iptables chain
  command: iptables -N '{{ item }}'
  changed_when: "chain.stderr != 'iptables: Chain already exists.'"
  failed_when: "chain.stderr != 'iptables: Chain already exists.' and chain.stderr != ''"
  register: chain
  become: true
  loop:
    - Always
    - Allow
    - Bogus
    - Enemies
    - Friends
  notify:
    - persist iptables

- name: INPUT chain
  ansible.builtin.iptables:
    table: filter
    chain: INPUT
    jump: "{{ item }}"
    wait: "{{ firewall_wait_lock_seconds }}"
  become: true
  loop: "{{ firewall_input_chain }}"
  notify:
    - persist iptables

- name: FORWARD chain
  ansible.builtin.iptables:
    table: filter
    chain: FORWARD
    jump: "{{ item }}"
    wait: "{{ firewall_wait_lock_seconds }}"
  become: true
  loop: "{{ firewall_forward_chain }}"
  notify:
    - persist iptables

- name: Add Bogus Packet Rules
  include_tasks: bogus_packets.yml

- name: Add Always Packet Rules
  include_tasks: always.yml

- name: Add Friends Packet Rules
  include_tasks: friends.yml

- name: Add Enemies Packet Rules
  include_tasks: enemies.yml

- name: Add Allow Packet Rules
  include_tasks: allow.yml