
- name: Create debmirror subdirectories
  ansible.builtin.file:
    state: directory
    path: "{{ mirror_dir }}/mirror/{{ aptmirror.mirror.name }}"
    mode: 0755
    owner: "{{ debmirror_user_name }}"
    group: "{{ debmirror_group_name }}"
  become: true
  loop_control:
    loop_var: aptmirror
    label: "{{ aptmirror.mirror.name }} ==> { handler='{{ aptmirror.handler | default('debmirror') }}', path='{{ mirror_dir }}/mirror/{{ aptmirror.mirror.name }}' }"
  loop: "{{ mirror_repos | selectattr('handler', '==', 'debmirror') }}"
  when:
    - aptmirror.handler == 'debmirror'

- name: Write debmirror config files
  ansible.builtin.template:
    src: debmirror.conf.j2
    dest: "/etc/debmirror.d/{{ aptmirror.mirror.name }}.conf"
    mode: 0640
    owner: root
    group: "{{ debmirror_group_name }}"
  become: true
  loop_control:
    loop_var: aptmirror
    label: "{{ aptmirror.mirror.name }} ==> { handler='{{ aptmirror.handler | default('debmirror') }}', path='/etc/debmirror.d/{{ aptmirror.mirror.name }}.conf' }"
  loop: "{{ mirror_repos | selectattr('handler', '==', 'debmirror') }}"
  when:
    - aptmirror.handler == 'debmirror'

- name: Create debmirror www Symlinks
  ansible.builtin.file:
    state: link
    src: "{{ mirror_dir }}/mirror/{{ aptmirror.mirror.name }}"
    path: "{{ mirror_dir }}/www/{{ aptmirror.mirror.name }}"
  loop_control:
    loop_var: aptmirror
    label: "{{ aptmirror.mirror.name }} ==> { handler='{{ aptmirror.handler | default('debmirror') }}', src='{{ mirror_dir }}/mirror/{{ aptmirror.mirror.name }}', path='{{ mirror_dir }}/www/{{ aptmirror.mirror.name }}' }"
  loop: "{{ mirror_repos | selectattr('handler', '==', 'debmirror') }}"
  become: true
  when:
    - aptmirror.handler == 'debmirror'
