
- name: Create apt mirror subdirectories
  ansible.builtin.file:
    state: directory
    path: "{{ mirror_dir }}/mirror/{{ aptmirror.remote.host }}/{{ aptmirror.remote.root }}"
    mode: 0755
    owner: "{{ debmirror_user_name }}"
    group: "{{ debmirror_group_name }}"
  become: true
  loop_control:
    loop_var: aptmirror
  loop: "{{ mirror_repos | default([]) }}"
  when:
    - aptmirror.handler | default('debmirror') == 'apt-mirror'

- name: Write debmirror config files
  ansible.builtin.template:
    src: apt-mirror.list.j2
    dest: "/etc/apt-mirror.d/{{ aptmirror.mirror.name }}.list"
    mode: 0640
    owner: root
    group: "{{ debmirror_group_name }}"
  become: true
  loop_control:
    loop_var: aptmirror
  loop: "{{ mirror_repos | default([]) }}"
  when:
    - aptmirror.handler | default('debmirror') == 'apt-mirror'

- name: Create www Symlinks
  ansible.builtin.file:
    state: link
    src: "{{ mirror_dir }}/mirror/{{ aptmirror.remote.host }}/{{ aptmirror.remote.root }}"
    path: "{{ mirror_dir }}/www/{{ aptmirror.mirror.name }}"
  loop_control:
    loop_var: aptmirror
  loop: "{{ mirror_repos | default([]) }}"
  become: true
  when:
    - aptmirror.handler | default('debmirror') == 'apt-mirror'
