- name: Create apt-mirror subdirectories
  ansible.builtin.file:
    state: directory
    path: "{{ mirror_dir }}/mirror/{{ aptmirror.remote.host }}/{{ aptmirror.remote.root }}"
    mode: 0755
    owner: "{{ debmirror_user_name }}"
    group: "{{ debmirror_group_name }}"
  become: true
  loop_control:
    loop_var: aptmirror
    label: "{{ aptmirror.mirror.name }} ==> { handler='{{ aptmirror.handler | default('debmirror') }}', path='{{ mirror_dir }}/mirror/{{ aptmirror.mirror.name }}' }"
  loop: "{{ mirror_repos | selectattr('handler', '==', 'apt-mirror') }}"
  when:
    - aptmirror.handler == 'apt-mirror'

- name: Write apt-mirror config files
  ansible.builtin.template:
    src: apt-mirror.list.j2
    dest: "/etc/apt-mirror.d/{{ aptmirror.mirror.name }}.list"
    mode: 0640
    owner: root
    group: "{{ debmirror_group_name }}"
  become: true
  loop_control:
    loop_var: aptmirror
    label: "{{ aptmirror.mirror.name }} ==> { handler='{{ aptmirror.handler | default('debmirror') }}', path='/etc/debmirror.d/{{ aptmirror.mirror.name }}.conf' }"
  loop: "{{ mirror_repos | selectattr('handler', '==', 'apt-mirror') }}"
  when:
    - aptmirror.handler == 'apt-mirror'

- name: Create apt-mirror www Symlinks
  ansible.builtin.file:
    state: link
    src: "{{ mirror_dir }}/mirror/{{ aptmirror.remote.host }}/{{ aptmirror.remote.root }}"
    path: "{{ mirror_dir }}/www/{{ aptmirror.mirror.name }}"
  loop_control:
    loop_var: aptmirror
    label: "{{ aptmirror.mirror.name }} ==> { handler='{{ aptmirror.handler | default('debmirror') }}', src='{{ mirror_dir }}/mirror/{{ aptmirror.mirror.name }}', path='{{ mirror_dir }}/www/{{ aptmirror.mirror.name }}' }"
  loop: "{{ mirror_repos | selectattr('handler', '==', 'apt-mirror') }}"
  become: true
  when:
    - aptmirror.handler == 'apt-mirror'
