- name: Configure NGINX
  ansible.builtin.include_role:
    name: nginxinc.nginx_core.nginx_config
  vars:
    nginx_config_cleanup: false
    nginx_config_html_demo_template_enable: false
    nginx_config_html_demo_template: []

    nginx_config_http_template_enable: true
    nginx_config_http_template:
      - template_file: http/default.conf.j2
        deployment_location: /etc/nginx/conf.d/default.conf
        config:
          ssl:
            certificate: "{{ debmirror_nginx_tls_cert_path }}"
            certificate_key: "{{ debmirror_nginx_tls_key_path }}"
          log:
            access:  # false  # Can alternatively be set to 'false'
              - path: /var/log/nginx/access.log  # Required
                format: main
                buffer: 1m
                gzip: 5  # Number -- Can alternatively be set to 'true'
                flush: 10h
            error:  # /var/log/nginx/error.log  # String, a list of strings, a dictionary, or a list of dictionaries. The 'file' variable is only required when setting a 'level'. This directive originally belongs to the NGINX core module, but we are making an exception.
              file: /var/log/nginx/error.log  # Required
              level: notice
            open_log_file_cache:  # Set to 'false' to set to 'off'
              max: 1000  # Required
              inactive: 20s
              min_uses: 2  # Number
              valid: 1m
          servers:
            - locations:
                - location: /
                  autoindex:
                    enable: true
                    exact_size: true
                    format: html
                    localtime: false
              core:
                access:
                  allow:
                    - all
                root: "{{ mirror_dir }}/www"
                server_name:
                  - localhost
                listen:
                  - address: 0.0.0.0
                    port: "{{ debmirror_nginx_http_port | int }}"
                    ssl: false
                    http2: false
                  - address: 0.0.0.0
                    port: "{{ debmirror_nginx_https_port | int }}"
                    ssl: true
                    http2: false
    nginx_config_status_enable: true
    nginx_config_status_template_file: http/status.conf.j2
    nginx_config_status_file_location: /etc/nginx/conf.d/status.conf
    nginx_config_status_port: "{{ debmirror_nginx_status_port | int }}"
    nginx_config_status_access_log:
      path: /var/log/nginx/access.log
    nginx_config_status_allow:
      - all
