- name: Install NGINX
  ansible.builtin.include_role:
    name: nginxinc.nginx_core.nginx
  vars:
    nginx_setup: install
    nginx_type: opensource
    nginx_debug_output: true
    nginx_selinux: true
    nginx_selinux_tcp_ports:
      - "{{ debmirror_http_port | int }}"
      - "{{ debmirror_https_port | int }}"
    nginx_logrotate_conf_enable: true
    nginx_logrotate_conf:
      paths:
        - /var/log/nginx/*.log
      options:
        - daily
        - missingok
        - rotate 14
        - compress
        - delaycompress
        - notifempty
        - sharedscripts
