- name: Include Tasks
  ansible.builtin.include_tasks:
    file: "{{ taskfile }}"
  loop_control:
    loop_var: taskfile
  loop:
    - create_users_and_groups.yml
    - install_mirror_software.yml
    - directories.yml
    - configure_apt-mirror.yml
    - configure_debmirror.yml
    - scripts.yml
    - gpg.yml
    - systemd_timer.yml
    - install_nginx.yml
    - configure_nginx.yml
    - configure_firewall.yml

