- name: Install SystemD Update Service and Timer
  ansible.builtin.template:
    src: "{{ systemd_timer_item.src }}"
    dest: "{{ systemd_timer_item.dest }}"
    mode: 0644
  become: true
  notify: systemd daemon reload
  loop_control:
    loop_var: systemd_timer_item
  loop:
    - src: debmirror.update.service.j2
      dest: /lib/systemd/system/debmirror.update.service
    - src: debmirror.update.timer.j2
      dest: /lib/systemd/system/debmirror.update.timer

- name: Flush handlers
  meta: flush_handlers

- name: Enable and Start debmirror Timer
  ansible.builtin.systemd:
    name: debmirror.update.timer
    state: started
    enabled: true
  become: true
