---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-log-shipping
  namespace: mssql
  labels:
    app-stack: mssql-server
    component: sql-server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  storageClassName: nfs-csi-retain
