kubernetes_zone: "{{ platform_environment }}.{{ cloudflare_zone }}"
sonatype_chart_repo_url: https://sonatype.github.io/helm3-charts/
sonatype_nexus_chart_version: 34.0.0
sonatype_nexus_release_namespace: sonatype-nexus
sonatype_nexus_cert_manager_issuer: letsencrypt-cloudflare-dns01
sonatype_nexus_cert_manager_issuer_kind: ClusterIssuer

sonatype_nexus_helm_values:
  ingress:
    enabled: true
    hostRepo: nexus.{{ kubernetes_zone }}
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/issuer: "{{ sonatype_nexus_cert_manager_issuer }}"
      cert-manager.io/issuer-kind: "{{ sonatype_nexus_cert_manager_issuer_kind }}"
    tls:
    - secretName: nexus-tls
      hosts:
        - nexus.{{ kubernetes_zone }}
  service:
    name: nexus
    enabled: true
    serviceType: ClusterIP
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    storageClass: truenas-iscsi-csi
    # existingClaim:
    # annotations:
    #  "helm.sh/resource-policy": keep
    storageSize: 500Gi
  resources:
    requests:
      cpu: 4
      memory: 4800Mi
    env:
      - name: install4jAddVmParams
        value: "-Xms1200M -Xmx1200M -XX:MaxDirectMemorySize=2G -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      - name: NEXUS_SECURITY_RANDOMPASSWORD
        value: "true"
