- name: download kubectl binary
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
  when: install_kubectl
  become: true

- name: download kubectl-cert-manager binary
  ansible.builtin.unarchive:
    src: https://github.com/jetstack/cert-manager/releases/download/v{{ cert_manager_helm_chart_version }}/kubectl-cert_manager-linux-amd64.tar.gz
    remote_src: true
    dest: /usr/local/bin
    mode: 0755
  become: true

- name: install certbot
  ansible.builtin.package:
    name: certbot
  become: true

- name: install required pip packages
  ansible.builtin.pip:
    name:
      - openshift
  become: true
