- hosts: localhost
  connection: local
  vars:
    helm_url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    jq_url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    kubectl_version: v1.23.5
    one_password_cli_url: https://cache.agilebits.com/dist/1P/op2/pkg/v2.0.2/op_linux_amd64_v2.0.2.zip
    krew_url: https://github.com/kubernetes-sigs/krew/releases/latest/download/krew-linux_amd64.tar.gz
  tasks:
    - name: create downloads directory
      ansible.builtin.file:
        path: /tmp/downloads
        state: directory

    - name: Download Scripts
      ansible.builtin.get_url:
        url: '{{ item.url }}'
        dest: /tmp/downloads/{{ item.filename }}
      loop:
        - url: '{{ krew_url }}'
          filename: kubectl-krew-linux-amd64.tar.gz
        - url: '{{ helm_url }}'
          filename: get_helm.sh
        - url: '{{ one_password_cli_url }}'
          filename: op_cli.zip

    - name: Download Binaries
      ansible.builtin.get_url:
        url: '{{ item.url }}'
        dest: /usr/local/bin/{{ item.filename }}
        mode: 0755
      become: true
      loop:
        - url: '{{ jq_url }}'
          filename: jq
        - url: https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl
          filename: kubectl

    - name: Extract Archives
      ansible.builtin.unarchive:
        src: "{{ item.src }}"
        dest: /tmp/downloads
      loop:
        - src: /home/automation-user/DellEMC-iDRACTools-Web-LX-9.5.0-4111_A00.tar.gz
        - src: /tmp/downloads/op_cli.zip
        - src: /tmp/downloads/kubectl-krew-linux-amd64.tar.gz

    - name: Move binaries.
      ansible.builtin.command:
        chdir: /tmp/downloads
        cmd: mv {{ executable.src }} {{ executable.dest }}
      become: true
      loop_control:
        loop_var: executable
      loop:
        - src: krew-linux_amd64
          dest: /usr/local/bin/kubectl-krew
        - src: op
          dest: /usr/local/bin/op

    - name: Install kubectl plugins
      ansible.builtin.command:
        cmd: kubectl krew install {{ item }}
      loop:
        - cert-manager
        - minio

    - name: Install Dell iDRAC Tools
      ansible.builtin.command:
        chdir: /tmp/downloads/iDRACTools/racadm
        cmd: ./install_racadm.sh
      become: true

    - name: Change Helm Installer Script Permissions
      ansible.builtin.file:
        path: /tmp/downloads/get_helm.sh
        mode: 0700

    - name: Install Helm
      ansible.builtin.command:
        chdir: /tmp/downloads
        cmd: ./get_helm.sh
      environment:
        PATH: "/usr/local/bin:{{ lookup('env', 'PATH') }}"
      become: true

    - name: Install Helm-Diff
      ansible.builtin.command:
        cmd: helm plugin install https://github.com/databus23/helm-diff
      environment:
        PATH: "/usr/local/bin:{{ lookup('env', 'PATH') }}"
      become: true

    - name: Remove downloads directory
      ansible.builtin.file:
        path: /tmp/downloads
        state: absent

    # - ansible.builtin.file:
    #     path: '{{ item.path }}'
    #     src: '{{ item.src }}'
    #     state: link
    #   become: true
    #   loop:
    #     - path: /usr/local/bin/racadm
    #       src: /opt/dell/srvadmin/bin/idracadm7

    - ansible.builtin.file:
        path: /ansible
        state: directory
        recurse: true
        owner: automation-user
        group: automation-user
      become: true
