---
keepalived_router_id: your-router-id
keepalived_state: BACKUP
keepalived_interface: eth0
keepalived_virtual_router_id: 50
keepalived_priority: 101
keepalived_auth_pass: 42
keepalived_vip: "{{ cluster_wildcard_vip }}"
keepalived_check_port: 6443

haproxy_user: haproxy
haproxy_group: haproxy
haproxy_role: default
haproxy_global_vars: []
haproxy_frontends:
  - name: api-server
    bind_address: "*"
    bind_port: 6443
    mode: tcp
    default_backend: api-server
    options:
      - tcplog
  - name: node-join
    bind_address: "*"
    bind_port: 9345
    mode: tcp
    default_backend: node-join
    options:
      - tcplog
  - name: http-ingress
    bind_address: "*"
    bind_port: 80
    mode: tcp
    default_backend: http-ingress
    options:
      - tcplog
  - name: https-ingress
    bind_address: "*"
    bind_port: 443
    mode: tcp
    default_backend: https-ingress
    options:
      - tcplog

haproxy_backends:
  - name: api-server
    mode: tcp
    port: 6443
    balance_method: roundrobin
    options:
      - httpchk GET /healthz
      - ssl-hello-chk
    http_checks:
      - expect status 200
    servers: "{{ rke2_controlplane_servers }}"
  - name: node-join
    mode: tcp
    port: 9345
    check_options: check-ssl verify none
    balance_method: roundrobin
    options:
      - httpchk GET /ping
    http_checks:
      - expect status 200
    servers: "{{ rke2_controlplane_servers }}"
  - name: http-ingress
    mode: tcp
    port: 80
    balance_method: roundrobin
    options:
      - httpchk GET /healthz
    http_checks:
      - expect status 200
    servers: "{{ rke2_ingress_servers }}"
  - name: https-ingress
    mode: tcp
    port: 443
    balance_method: roundrobin
    options:
      - httpchk GET /healthz
      - ssl-hello-chk
    http_checks:
      - expect status 200
    servers: "{{ rke2_ingress_servers }}"

