name: Build and Publish Docker Image

on:
  workflow_call:
    inputs:
      DOCKER_IMAGENAME:
        required: true
        type: string
      DOCKER_USERNAME:
        required: true
        type: string
      PUSH_IMAGE:
        required: true
        type: boolean

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    environment: Docker

    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ inputs.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: docker/${{ inputs.DOCKER_USERNAME }}/${{ inputs.DOCKER_IMAGENAME }}
          # Note: tags has to be all lower-case
          tags: |
            ${{ inputs.DOCKER_USERNAME }}/${{ inputs.DOCKER_IMAGENAME }}:latest
          # build on feature branches, push only on main branch
          push: ${{ inputs.PUSH_IMAGE }}
