# This is a basic workflow to help you get started with Actions

name: CI | Docker | estenrye/platform9-ansible


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - ansible/playbooks/platform9/**
      - .github/workflows/CI-estenrye-platform9-ansible.yml
  pull_request:
    branches: [ master ]
    paths:
      - mssql-server-tools/**
      - .github/workflows/CI-estenrye-platform9-ansible.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Docker
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: estenrye/platform9-ansible
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
        context: mssql-server-tools
        dockerfile: mssql-server-tools/Dockerfile
