name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    paths:
      - docker/estenrye/ubuntu-autoinstall-iso/**
      - .github/workflows/CI-estenrye-ubuntu-autoinstall-iso.yml

  # run it during pull request
  pull_request:
    paths:
      - docker/estenrye/ubuntu-autoinstall-iso/**
      - .github/workflows/CI-estenrye-ubuntu-autoinstall-iso.yml

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    environment: Docker
    env:
      DOCKER_IMAGENAME: ubuntu-autoinstall-iso
      DOCKER_USERNAME: estenrye
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: docker/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGENAME }}
          # Note: tags has to be all lower-case
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGENAME }}:latest
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/master' }}
