name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    paths:
      - docker/estenrye/ubuntu-autoinstall-iso/**
      - .github/workflows/CI-estenrye-ubuntu-autoinstall-iso.yml
      - .github/workflows/CI-Docker-Image-Build-Template.yml

  # run it during pull request
  pull_request:
    paths:
      - docker/estenrye/ubuntu-autoinstall-iso/**
      - .github/workflows/CI-estenrye-ubuntu-autoinstall-iso.yml
      - .github/workflows/CI-Docker-Image-Build-Template.yml

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    environment: Docker
    env:
      DOCKER_IMAGENAME: ubuntu-autoinstall-iso
      DOCKER_USERNAME: estenrye
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: .github/workflows/CI-Docker-Image-Build-Template.yml
        with:
          DOCKER_IMAGENAME: ubuntu-autoinstall-iso
          DOCKER_USERNAME: estenrye
          PUSH_IMAGE: ${{ github.ref == 'refs/heads/master' }}
